/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_DaApiWrapper_WRAP_H_
#define SWIG_DaApiWrapper_WRAP_H_

class SwigDirector_IMarketEvent : public Directaccess::IMarketEvent, public Swig::Director {

public:
    SwigDirector_IMarketEvent();
    virtual void OnFrontConnected();
    virtual void OnFrontDisconnected(int iReason);
    virtual void OnHeartBeatWarning(int iTimeLapse);
    virtual void OnRspRawData(char const *rawData);
    virtual void OnRspUserLogin(Directaccess::CMarketRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
    virtual void OnRspTradeDate(Directaccess::CMarketRspTradeDateField *pRspTradeDate,Directaccess::CMarketRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
    virtual void OnRspBrokerData(Directaccess::CMarketRspBrokerDataField *pRspBrokerData,Directaccess::CMarketRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
    virtual void OnRspMarketData(Directaccess::CMarketRspMarketDataField *pRspMarketData,Directaccess::CMarketRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
    virtual void OnRspUserLogout(Directaccess::CMarketRspInfoField *pRspInfo,int iRequestID,bool bIsLast);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback1_t)(int);
    typedef void (SWIGSTDCALL* SWIG_Callback2_t)(int);
    typedef void (SWIGSTDCALL* SWIG_Callback3_t)(char *);
    typedef void (SWIGSTDCALL* SWIG_Callback4_t)(void *, int, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback5_t)(void *, void *, int, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback6_t)(void *, void *, int, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback7_t)(void *, void *, int, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback8_t)(void *, int, unsigned int);
    void swig_connect_director(SWIG_Callback0_t callbackOnFrontConnected, SWIG_Callback1_t callbackOnFrontDisconnected, SWIG_Callback2_t callbackOnHeartBeatWarning, SWIG_Callback3_t callbackOnRspRawData, SWIG_Callback4_t callbackOnRspUserLogin, SWIG_Callback5_t callbackOnRspTradeDate, SWIG_Callback6_t callbackOnRspBrokerData, SWIG_Callback7_t callbackOnRspMarketData, SWIG_Callback8_t callbackOnRspUserLogout);

private:
    SWIG_Callback0_t swig_callbackOnFrontConnected;
    SWIG_Callback1_t swig_callbackOnFrontDisconnected;
    SWIG_Callback2_t swig_callbackOnHeartBeatWarning;
    SWIG_Callback3_t swig_callbackOnRspRawData;
    SWIG_Callback4_t swig_callbackOnRspUserLogin;
    SWIG_Callback5_t swig_callbackOnRspTradeDate;
    SWIG_Callback6_t swig_callbackOnRspBrokerData;
    SWIG_Callback7_t swig_callbackOnRspMarketData;
    SWIG_Callback8_t swig_callbackOnRspUserLogout;
    void swig_init_callbacks();
};

class SwigDirector_IFutureEvent : public Directaccess::IFutureEvent, public Swig::Director {

public:
    SwigDirector_IFutureEvent();
    virtual void OnFrontConnected();
    virtual void OnFrontDisconnected(int iReason);
    virtual void OnHeartBeatWarning(int iTimeLapse);
    virtual void OnRspNeedVerify(bool bFirstLogin,bool bHasSetQA);
    virtual void OnRspUserLogin(Directaccess::CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
    virtual void OnRspUserLogout(Directaccess::CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
    virtual void OnRspVerifyCode(Directaccess::CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
    virtual void OnRspSafeVerify(Directaccess::CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
    virtual void OnRspSetVerifyQA(Directaccess::CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
    virtual void OnRspAccount(Directaccess::CFutureRspAccountField *pRspAccount,Directaccess::CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
    virtual void OnRspQuestion(Directaccess::CFutureRspQuestionField *pRspVersion,Directaccess::CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
    virtual void OnRspOrderInsert(Directaccess::CFutureRspOrderInsertField *pRspOrderInsert,Directaccess::CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
    virtual void OnRspOrderModify(Directaccess::CFutureRspOrderModifyField *pRspOrderModify,Directaccess::CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
    virtual void OnRspOrderCancel(Directaccess::CFutureRspOrderCancelField *pRspOrderCancel,Directaccess::CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
    virtual void OnRspPasswordUpdate(Directaccess::CFutureRspPasswordUpdateField *pRspPasswordUpdate,Directaccess::CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
    virtual void OnRtnTrade(Directaccess::CFutureRtnTradeField *pRtnTrade,Directaccess::CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
    virtual void OnRtnOrder(Directaccess::CFutureRtnOrderField *pRtnOrder,Directaccess::CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
    virtual void OnRtnCapital(Directaccess::CFutureRtnCapitalField *pRtnCapital,Directaccess::CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
    virtual void OnRtnPosition(Directaccess::CFutureRtnPositionField *pRtnPosition,Directaccess::CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
    virtual void OnRspQryOrder(Directaccess::CFutureRspOrderField *pRspOrder,Directaccess::CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
    virtual void OnRspQryTrade(Directaccess::CFutureRspTradeField *pRspTrade,Directaccess::CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
    virtual void OnRspQryCapital(Directaccess::CFutureRspCapitalField *pRspCapital,Directaccess::CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
    virtual void OnRspQryVersion(Directaccess::CFutureRspVersionField *pRspVersion,Directaccess::CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
    virtual void OnRspQryPosition(Directaccess::CFutureRspPositionField *pRspPosition,Directaccess::CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
    virtual void OnRspQryCurrency(Directaccess::CFutureRspCurrencyField *pRspCurrency,Directaccess::CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
    virtual void OnRspQryExchange(Directaccess::CFutureRspExchangeField *pRspExchange,Directaccess::CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
    virtual void OnRspQryStrategy(Directaccess::CFutureRspStrategyField *pRspStrategy,Directaccess::CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
    virtual void OnRspQryCommodity(Directaccess::CFutureRspCommodityField *pRspCommodity,Directaccess::CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
    virtual void OnRspQryInstrument(Directaccess::CFutureRspInstrumentField *pRspInstrument,Directaccess::CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
    virtual void OnRspQryExchangeTime(Directaccess::CFutureRspExchangeTimeField *pRspExchangeTime,Directaccess::CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
    virtual void OnRspQryCommodityTime(Directaccess::CFutureRspCommodityTimeField *pRspCommodityTime,Directaccess::CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
    virtual void OnRspQryTotalPosition(Directaccess::CFutureRspTotalPositionField *pRspTotalPosition,Directaccess::CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
    virtual void OnRspQryStrategyDetail(Directaccess::CFutureRspStrategyDetailField *pRspStrategyDetail,Directaccess::CFutureRspInfoField *pRspInfo,int iRequestID,bool bIsLast);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback1_t)(int);
    typedef void (SWIGSTDCALL* SWIG_Callback2_t)(int);
    typedef void (SWIGSTDCALL* SWIG_Callback3_t)(unsigned int, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback4_t)(void *, int, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback5_t)(void *, int, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback6_t)(void *, int, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback7_t)(void *, int, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback8_t)(void *, int, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback9_t)(void *, void *, int, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback10_t)(void *, void *, int, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback11_t)(void *, void *, int, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback12_t)(void *, void *, int, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback13_t)(void *, void *, int, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback14_t)(void *, void *, int, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback15_t)(void *, void *, int, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback16_t)(void *, void *, int, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback17_t)(void *, void *, int, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback18_t)(void *, void *, int, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback19_t)(void *, void *, int, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback20_t)(void *, void *, int, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback21_t)(void *, void *, int, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback22_t)(void *, void *, int, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback23_t)(void *, void *, int, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback24_t)(void *, void *, int, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback25_t)(void *, void *, int, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback26_t)(void *, void *, int, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback27_t)(void *, void *, int, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback28_t)(void *, void *, int, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback29_t)(void *, void *, int, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback30_t)(void *, void *, int, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback31_t)(void *, void *, int, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback32_t)(void *, void *, int, unsigned int);
    void swig_connect_director(SWIG_Callback0_t callbackOnFrontConnected, SWIG_Callback1_t callbackOnFrontDisconnected, SWIG_Callback2_t callbackOnHeartBeatWarning, SWIG_Callback3_t callbackOnRspNeedVerify, SWIG_Callback4_t callbackOnRspUserLogin, SWIG_Callback5_t callbackOnRspUserLogout, SWIG_Callback6_t callbackOnRspVerifyCode, SWIG_Callback7_t callbackOnRspSafeVerify, SWIG_Callback8_t callbackOnRspSetVerifyQA, SWIG_Callback9_t callbackOnRspAccount, SWIG_Callback10_t callbackOnRspQuestion, SWIG_Callback11_t callbackOnRspOrderInsert, SWIG_Callback12_t callbackOnRspOrderModify, SWIG_Callback13_t callbackOnRspOrderCancel, SWIG_Callback14_t callbackOnRspPasswordUpdate, SWIG_Callback15_t callbackOnRtnTrade, SWIG_Callback16_t callbackOnRtnOrder, SWIG_Callback17_t callbackOnRtnCapital, SWIG_Callback18_t callbackOnRtnPosition, SWIG_Callback19_t callbackOnRspQryOrder, SWIG_Callback20_t callbackOnRspQryTrade, SWIG_Callback21_t callbackOnRspQryCapital, SWIG_Callback22_t callbackOnRspQryVersion, SWIG_Callback23_t callbackOnRspQryPosition, SWIG_Callback24_t callbackOnRspQryCurrency, SWIG_Callback25_t callbackOnRspQryExchange, SWIG_Callback26_t callbackOnRspQryStrategy, SWIG_Callback27_t callbackOnRspQryCommodity, SWIG_Callback28_t callbackOnRspQryInstrument, SWIG_Callback29_t callbackOnRspQryExchangeTime, SWIG_Callback30_t callbackOnRspQryCommodityTime, SWIG_Callback31_t callbackOnRspQryTotalPosition, SWIG_Callback32_t callbackOnRspQryStrategyDetail);

private:
    SWIG_Callback0_t swig_callbackOnFrontConnected;
    SWIG_Callback1_t swig_callbackOnFrontDisconnected;
    SWIG_Callback2_t swig_callbackOnHeartBeatWarning;
    SWIG_Callback3_t swig_callbackOnRspNeedVerify;
    SWIG_Callback4_t swig_callbackOnRspUserLogin;
    SWIG_Callback5_t swig_callbackOnRspUserLogout;
    SWIG_Callback6_t swig_callbackOnRspVerifyCode;
    SWIG_Callback7_t swig_callbackOnRspSafeVerify;
    SWIG_Callback8_t swig_callbackOnRspSetVerifyQA;
    SWIG_Callback9_t swig_callbackOnRspAccount;
    SWIG_Callback10_t swig_callbackOnRspQuestion;
    SWIG_Callback11_t swig_callbackOnRspOrderInsert;
    SWIG_Callback12_t swig_callbackOnRspOrderModify;
    SWIG_Callback13_t swig_callbackOnRspOrderCancel;
    SWIG_Callback14_t swig_callbackOnRspPasswordUpdate;
    SWIG_Callback15_t swig_callbackOnRtnTrade;
    SWIG_Callback16_t swig_callbackOnRtnOrder;
    SWIG_Callback17_t swig_callbackOnRtnCapital;
    SWIG_Callback18_t swig_callbackOnRtnPosition;
    SWIG_Callback19_t swig_callbackOnRspQryOrder;
    SWIG_Callback20_t swig_callbackOnRspQryTrade;
    SWIG_Callback21_t swig_callbackOnRspQryCapital;
    SWIG_Callback22_t swig_callbackOnRspQryVersion;
    SWIG_Callback23_t swig_callbackOnRspQryPosition;
    SWIG_Callback24_t swig_callbackOnRspQryCurrency;
    SWIG_Callback25_t swig_callbackOnRspQryExchange;
    SWIG_Callback26_t swig_callbackOnRspQryStrategy;
    SWIG_Callback27_t swig_callbackOnRspQryCommodity;
    SWIG_Callback28_t swig_callbackOnRspQryInstrument;
    SWIG_Callback29_t swig_callbackOnRspQryExchangeTime;
    SWIG_Callback30_t swig_callbackOnRspQryCommodityTime;
    SWIG_Callback31_t swig_callbackOnRspQryTotalPosition;
    SWIG_Callback32_t swig_callbackOnRspQryStrategyDetail;
    void swig_init_callbacks();
};

class SwigDirector_IStockEvent : public Directaccess::IStockEvent, public Swig::Director {

public:
    SwigDirector_IStockEvent();
    virtual void OnFrontConnected();
    virtual void OnFrontDisconnected(int iReason);
    virtual void OnHeartBeatWarning(int iTimeLapse);
    virtual void OnRspNeedVerify(bool bFirstLogin,bool bHasSetQA);
    virtual void OnRspUserLogin(Directaccess::CStockRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
    virtual void OnRspUserLogout(Directaccess::CStockRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
    virtual void OnRspVerifyCode(Directaccess::CStockRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
    virtual void OnRspSafeVerify(Directaccess::CStockRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
    virtual void OnRspSetVerifyQA(Directaccess::CStockRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
    virtual void OnRspAccount(Directaccess::CStockRspAccountField *pRspAccount,Directaccess::CStockRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
    virtual void OnRspQuestion(Directaccess::CStockRspQuestionField *pRspQuestion,Directaccess::CStockRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
    virtual void OnRspOrderInsert(Directaccess::CStockRspOrderInsertField *pRspOrderInsert,Directaccess::CStockRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
    virtual void OnRspOrderModify(Directaccess::CStockRspOrderModifyField *pRspOrderModify,Directaccess::CStockRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
    virtual void OnRspOrderCancel(Directaccess::CStockRspOrderCancelField *pRspOrderCancel,Directaccess::CStockRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
    virtual void OnRspPasswordUpdate(Directaccess::CStockRspPasswordUpdateField *pRspPasswordUpdate,Directaccess::CStockRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
    virtual void OnRtnTrade(Directaccess::CStockRtnTradeField *pRtnTrade,Directaccess::CStockRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
    virtual void OnRtnOrder(Directaccess::CStockRtnOrderField *pRtnOrder,Directaccess::CStockRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
    virtual void OnRtnCapital(Directaccess::CStockRtnCapitalField *pRtnCapital,Directaccess::CStockRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
    virtual void OnRtnPosition(Directaccess::CStockRtnPositionField *pRtnPosition,Directaccess::CStockRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
    virtual void OnRspQryTick(Directaccess::CStockRspTickField *pRspTick,Directaccess::CStockRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
    virtual void OnRspQryOrder(Directaccess::CStockRspOrderField *pRspOrder,Directaccess::CStockRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
    virtual void OnRspQryTrade(Directaccess::CStockRspTradeField *pRspTrade,Directaccess::CStockRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
    virtual void OnRspQryCapital(Directaccess::CStockRspCapitalField *pRspCapital,Directaccess::CStockRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
    virtual void OnRspQryVersion(Directaccess::CStockRspVersionField *pRspVersion,Directaccess::CStockRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
    virtual void OnRspQryPosition(Directaccess::CStockRspPositionField *pRspPosition,Directaccess::CStockRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
    virtual void OnRspQryCurrency(Directaccess::CStockRspCurrencyField *pRspCurrency,Directaccess::CStockRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
    virtual void OnRspQryExchange(Directaccess::CStockRspExchangeField *pRspExchange,Directaccess::CStockRspInfoField *pRspInfo,int iRequestID,bool bIsLast);
    virtual void OnRspQryInstrument(Directaccess::CStockRspInstrumentField *pRspInstrument,Directaccess::CStockRspInfoField *pRspInfo,int iRequestID,bool bIsLast);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback1_t)(int);
    typedef void (SWIGSTDCALL* SWIG_Callback2_t)(int);
    typedef void (SWIGSTDCALL* SWIG_Callback3_t)(unsigned int, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback4_t)(void *, int, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback5_t)(void *, int, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback6_t)(void *, int, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback7_t)(void *, int, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback8_t)(void *, int, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback9_t)(void *, void *, int, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback10_t)(void *, void *, int, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback11_t)(void *, void *, int, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback12_t)(void *, void *, int, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback13_t)(void *, void *, int, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback14_t)(void *, void *, int, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback15_t)(void *, void *, int, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback16_t)(void *, void *, int, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback17_t)(void *, void *, int, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback18_t)(void *, void *, int, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback19_t)(void *, void *, int, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback20_t)(void *, void *, int, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback21_t)(void *, void *, int, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback22_t)(void *, void *, int, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback23_t)(void *, void *, int, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback24_t)(void *, void *, int, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback25_t)(void *, void *, int, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback26_t)(void *, void *, int, unsigned int);
    typedef void (SWIGSTDCALL* SWIG_Callback27_t)(void *, void *, int, unsigned int);
    void swig_connect_director(SWIG_Callback0_t callbackOnFrontConnected, SWIG_Callback1_t callbackOnFrontDisconnected, SWIG_Callback2_t callbackOnHeartBeatWarning, SWIG_Callback3_t callbackOnRspNeedVerify, SWIG_Callback4_t callbackOnRspUserLogin, SWIG_Callback5_t callbackOnRspUserLogout, SWIG_Callback6_t callbackOnRspVerifyCode, SWIG_Callback7_t callbackOnRspSafeVerify, SWIG_Callback8_t callbackOnRspSetVerifyQA, SWIG_Callback9_t callbackOnRspAccount, SWIG_Callback10_t callbackOnRspQuestion, SWIG_Callback11_t callbackOnRspOrderInsert, SWIG_Callback12_t callbackOnRspOrderModify, SWIG_Callback13_t callbackOnRspOrderCancel, SWIG_Callback14_t callbackOnRspPasswordUpdate, SWIG_Callback15_t callbackOnRtnTrade, SWIG_Callback16_t callbackOnRtnOrder, SWIG_Callback17_t callbackOnRtnCapital, SWIG_Callback18_t callbackOnRtnPosition, SWIG_Callback19_t callbackOnRspQryTick, SWIG_Callback20_t callbackOnRspQryOrder, SWIG_Callback21_t callbackOnRspQryTrade, SWIG_Callback22_t callbackOnRspQryCapital, SWIG_Callback23_t callbackOnRspQryVersion, SWIG_Callback24_t callbackOnRspQryPosition, SWIG_Callback25_t callbackOnRspQryCurrency, SWIG_Callback26_t callbackOnRspQryExchange, SWIG_Callback27_t callbackOnRspQryInstrument);

private:
    SWIG_Callback0_t swig_callbackOnFrontConnected;
    SWIG_Callback1_t swig_callbackOnFrontDisconnected;
    SWIG_Callback2_t swig_callbackOnHeartBeatWarning;
    SWIG_Callback3_t swig_callbackOnRspNeedVerify;
    SWIG_Callback4_t swig_callbackOnRspUserLogin;
    SWIG_Callback5_t swig_callbackOnRspUserLogout;
    SWIG_Callback6_t swig_callbackOnRspVerifyCode;
    SWIG_Callback7_t swig_callbackOnRspSafeVerify;
    SWIG_Callback8_t swig_callbackOnRspSetVerifyQA;
    SWIG_Callback9_t swig_callbackOnRspAccount;
    SWIG_Callback10_t swig_callbackOnRspQuestion;
    SWIG_Callback11_t swig_callbackOnRspOrderInsert;
    SWIG_Callback12_t swig_callbackOnRspOrderModify;
    SWIG_Callback13_t swig_callbackOnRspOrderCancel;
    SWIG_Callback14_t swig_callbackOnRspPasswordUpdate;
    SWIG_Callback15_t swig_callbackOnRtnTrade;
    SWIG_Callback16_t swig_callbackOnRtnOrder;
    SWIG_Callback17_t swig_callbackOnRtnCapital;
    SWIG_Callback18_t swig_callbackOnRtnPosition;
    SWIG_Callback19_t swig_callbackOnRspQryTick;
    SWIG_Callback20_t swig_callbackOnRspQryOrder;
    SWIG_Callback21_t swig_callbackOnRspQryTrade;
    SWIG_Callback22_t swig_callbackOnRspQryCapital;
    SWIG_Callback23_t swig_callbackOnRspQryVersion;
    SWIG_Callback24_t swig_callbackOnRspQryPosition;
    SWIG_Callback25_t swig_callbackOnRspQryCurrency;
    SWIG_Callback26_t swig_callbackOnRspQryExchange;
    SWIG_Callback27_t swig_callbackOnRspQryInstrument;
    void swig_init_callbacks();
};


#endif
