//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace DAApi.Net {

public class CFutureReqSetVerifyQAField : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CFutureReqSetVerifyQAField(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CFutureReqSetVerifyQAField obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CFutureReqSetVerifyQAField obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~CFutureReqSetVerifyQAField() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          DaApiWrapperPINVOKE.delete_CFutureReqSetVerifyQAField(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string UserId {
    set {
      DaApiWrapperPINVOKE.CFutureReqSetVerifyQAField_UserId_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureReqSetVerifyQAField_UserId_get(swigCPtr);
      return ret;
    } 
  }

  public string UserPwd {
    set {
      DaApiWrapperPINVOKE.CFutureReqSetVerifyQAField_UserPwd_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureReqSetVerifyQAField_UserPwd_get(swigCPtr);
      return ret;
    } 
  }

  public string Type {
    set {
      DaApiWrapperPINVOKE.CFutureReqSetVerifyQAField_Type_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureReqSetVerifyQAField_Type_get(swigCPtr);
      return ret;
    } 
  }

  public string Question {
    set {
      DaApiWrapperPINVOKE.CFutureReqSetVerifyQAField_Question_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureReqSetVerifyQAField_Question_get(swigCPtr);
      return ret;
    } 
  }

  public string Answer {
    set {
      DaApiWrapperPINVOKE.CFutureReqSetVerifyQAField_Answer_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureReqSetVerifyQAField_Answer_get(swigCPtr);
      return ret;
    } 
  }

  public string MobileNumber {
    set {
      DaApiWrapperPINVOKE.CFutureReqSetVerifyQAField_MobileNumber_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureReqSetVerifyQAField_MobileNumber_get(swigCPtr);
      return ret;
    } 
  }

  public string VerifyCode {
    set {
      DaApiWrapperPINVOKE.CFutureReqSetVerifyQAField_VerifyCode_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureReqSetVerifyQAField_VerifyCode_get(swigCPtr);
      return ret;
    } 
  }

  public string SaveMac {
    set {
      DaApiWrapperPINVOKE.CFutureReqSetVerifyQAField_SaveMac_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureReqSetVerifyQAField_SaveMac_get(swigCPtr);
      return ret;
    } 
  }

  public string ErrorDescription {
    set {
      DaApiWrapperPINVOKE.CFutureReqSetVerifyQAField_ErrorDescription_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureReqSetVerifyQAField_ErrorDescription_get(swigCPtr);
      return ret;
    } 
  }

  public CFutureReqSetVerifyQAField() : this(DaApiWrapperPINVOKE.new_CFutureReqSetVerifyQAField(), true) {
  }

}

}
