//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace DAApi.Net {

public class CFutureRspTickField : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CFutureRspTickField(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CFutureRspTickField obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CFutureRspTickField obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~CFutureRspTickField() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          DaApiWrapperPINVOKE.delete_CFutureRspTickField(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string UpperTickCode {
    set {
      DaApiWrapperPINVOKE.CFutureRspTickField_UpperTickCode_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspTickField_UpperTickCode_get(swigCPtr);
      return ret;
    } 
  }

  public string PriceFrom {
    set {
      DaApiWrapperPINVOKE.CFutureRspTickField_PriceFrom_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspTickField_PriceFrom_get(swigCPtr);
      return ret;
    } 
  }

  public string UpperTick {
    set {
      DaApiWrapperPINVOKE.CFutureRspTickField_UpperTick_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspTickField_UpperTick_get(swigCPtr);
      return ret;
    } 
  }

  public string ProductDot {
    set {
      DaApiWrapperPINVOKE.CFutureRspTickField_ProductDot_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspTickField_ProductDot_get(swigCPtr);
      return ret;
    } 
  }

  public string DotNum {
    set {
      DaApiWrapperPINVOKE.CFutureRspTickField_DotNum_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspTickField_DotNum_get(swigCPtr);
      return ret;
    } 
  }

  public string LowerTick {
    set {
      DaApiWrapperPINVOKE.CFutureRspTickField_LowerTick_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspTickField_LowerTick_get(swigCPtr);
      return ret;
    } 
  }

  public CFutureRspTickField() : this(DaApiWrapperPINVOKE.new_CFutureRspTickField(), true) {
  }

}

}
