//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace DAApi.Net {

public class CFutureRspPositionField : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CFutureRspPositionField(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CFutureRspPositionField obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CFutureRspPositionField obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~CFutureRspPositionField() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          DaApiWrapperPINVOKE.delete_CFutureRspPositionField(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string MatchDate {
    set {
      DaApiWrapperPINVOKE.CFutureRspPositionField_MatchDate_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspPositionField_MatchDate_get(swigCPtr);
      return ret;
    } 
  }

  public string MatchNo {
    set {
      DaApiWrapperPINVOKE.CFutureRspPositionField_MatchNo_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspPositionField_MatchNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ClientNo {
    set {
      DaApiWrapperPINVOKE.CFutureRspPositionField_ClientNo_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspPositionField_ClientNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeNo {
    set {
      DaApiWrapperPINVOKE.CFutureRspPositionField_ExchangeNo_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspPositionField_ExchangeNo_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityNo {
    set {
      DaApiWrapperPINVOKE.CFutureRspPositionField_CommodityNo_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspPositionField_CommodityNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ContractNo {
    set {
      DaApiWrapperPINVOKE.CFutureRspPositionField_ContractNo_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspPositionField_ContractNo_get(swigCPtr);
      return ret;
    } 
  }

  public string Direct {
    set {
      DaApiWrapperPINVOKE.CFutureRspPositionField_Direct_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspPositionField_Direct_get(swigCPtr);
      return ret;
    } 
  }

  public int HoldVol {
    set {
      DaApiWrapperPINVOKE.CFutureRspPositionField_HoldVol_set(swigCPtr, value);
    } 
    get {
      int ret = DaApiWrapperPINVOKE.CFutureRspPositionField_HoldVol_get(swigCPtr);
      return ret;
    } 
  }

  public double HoldPrice {
    set {
      DaApiWrapperPINVOKE.CFutureRspPositionField_HoldPrice_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CFutureRspPositionField_HoldPrice_get(swigCPtr);
      return ret;
    } 
  }

  public string CurrencyNo {
    set {
      DaApiWrapperPINVOKE.CFutureRspPositionField_CurrencyNo_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspPositionField_CurrencyNo_get(swigCPtr);
      return ret;
    } 
  }

  public double ForciblyPrice {
    set {
      DaApiWrapperPINVOKE.CFutureRspPositionField_ForciblyPrice_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CFutureRspPositionField_ForciblyPrice_get(swigCPtr);
      return ret;
    } 
  }

  public string Account {
    set {
      DaApiWrapperPINVOKE.CFutureRspPositionField_Account_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspPositionField_Account_get(swigCPtr);
      return ret;
    } 
  }

  public string HoldType {
    set {
      DaApiWrapperPINVOKE.CFutureRspPositionField_HoldType_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspPositionField_HoldType_get(swigCPtr);
      return ret;
    } 
  }

  public string DeliveryDate {
    set {
      DaApiWrapperPINVOKE.CFutureRspPositionField_DeliveryDate_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspPositionField_DeliveryDate_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeName {
    set {
      DaApiWrapperPINVOKE.CFutureRspPositionField_ExchangeName_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspPositionField_ExchangeName_get(swigCPtr);
      return ret;
    } 
  }

  public string CurrencyName {
    set {
      DaApiWrapperPINVOKE.CFutureRspPositionField_CurrencyName_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspPositionField_CurrencyName_get(swigCPtr);
      return ret;
    } 
  }

  public string ContCode {
    set {
      DaApiWrapperPINVOKE.CFutureRspPositionField_ContCode_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspPositionField_ContCode_get(swigCPtr);
      return ret;
    } 
  }

  public double HoldMargin {
    set {
      DaApiWrapperPINVOKE.CFutureRspPositionField_HoldMargin_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CFutureRspPositionField_HoldMargin_get(swigCPtr);
      return ret;
    } 
  }

  public CFutureRspPositionField() : this(DaApiWrapperPINVOKE.new_CFutureRspPositionField(), true) {
  }

}

}
