//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace DAApi.Net {

public class CFutureRtnOrderField : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CFutureRtnOrderField(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CFutureRtnOrderField obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CFutureRtnOrderField obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~CFutureRtnOrderField() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          DaApiWrapperPINVOKE.delete_CFutureRtnOrderField(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string LocalNo {
    set {
      DaApiWrapperPINVOKE.CFutureRtnOrderField_LocalNo_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRtnOrderField_LocalNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeCode {
    set {
      DaApiWrapperPINVOKE.CFutureRtnOrderField_ExchangeCode_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRtnOrderField_ExchangeCode_get(swigCPtr);
      return ret;
    } 
  }

  public string ContractCode {
    set {
      DaApiWrapperPINVOKE.CFutureRtnOrderField_ContractCode_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRtnOrderField_ContractCode_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderNo {
    set {
      DaApiWrapperPINVOKE.CFutureRtnOrderField_OrderNo_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRtnOrderField_OrderNo_get(swigCPtr);
      return ret;
    } 
  }

  public int OrderQty {
    set {
      DaApiWrapperPINVOKE.CFutureRtnOrderField_OrderQty_set(swigCPtr, value);
    } 
    get {
      int ret = DaApiWrapperPINVOKE.CFutureRtnOrderField_OrderQty_get(swigCPtr);
      return ret;
    } 
  }

  public int FilledQty {
    set {
      DaApiWrapperPINVOKE.CFutureRtnOrderField_FilledQty_set(swigCPtr, value);
    } 
    get {
      int ret = DaApiWrapperPINVOKE.CFutureRtnOrderField_FilledQty_get(swigCPtr);
      return ret;
    } 
  }

  public double FilledAvgPrice {
    set {
      DaApiWrapperPINVOKE.CFutureRtnOrderField_FilledAvgPrice_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CFutureRtnOrderField_FilledAvgPrice_get(swigCPtr);
      return ret;
    } 
  }

  public int LongPositionQty {
    set {
      DaApiWrapperPINVOKE.CFutureRtnOrderField_LongPositionQty_set(swigCPtr, value);
    } 
    get {
      int ret = DaApiWrapperPINVOKE.CFutureRtnOrderField_LongPositionQty_get(swigCPtr);
      return ret;
    } 
  }

  public double LongPosAveragePrx {
    set {
      DaApiWrapperPINVOKE.CFutureRtnOrderField_LongPosAveragePrx_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CFutureRtnOrderField_LongPosAveragePrx_get(swigCPtr);
      return ret;
    } 
  }

  public double CNLongPosAveragePrx {
    set {
      DaApiWrapperPINVOKE.CFutureRtnOrderField_CNLongPosAveragePrx_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CFutureRtnOrderField_CNLongPosAveragePrx_get(swigCPtr);
      return ret;
    } 
  }

  public int ShortPositionQty {
    set {
      DaApiWrapperPINVOKE.CFutureRtnOrderField_ShortPositionQty_set(swigCPtr, value);
    } 
    get {
      int ret = DaApiWrapperPINVOKE.CFutureRtnOrderField_ShortPositionQty_get(swigCPtr);
      return ret;
    } 
  }

  public double ShortPosAveragePrx {
    set {
      DaApiWrapperPINVOKE.CFutureRtnOrderField_ShortPosAveragePrx_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CFutureRtnOrderField_ShortPosAveragePrx_get(swigCPtr);
      return ret;
    } 
  }

  public double CNShortPosAveragePrx {
    set {
      DaApiWrapperPINVOKE.CFutureRtnOrderField_CNShortPosAveragePrx_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CFutureRtnOrderField_CNShortPosAveragePrx_get(swigCPtr);
      return ret;
    } 
  }

  public string IsCanceled {
    set {
      DaApiWrapperPINVOKE.CFutureRtnOrderField_IsCanceled_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRtnOrderField_IsCanceled_get(swigCPtr);
      return ret;
    } 
  }

  public double FilledTotalFee {
    set {
      DaApiWrapperPINVOKE.CFutureRtnOrderField_FilledTotalFee_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CFutureRtnOrderField_FilledTotalFee_get(swigCPtr);
      return ret;
    } 
  }

  public int SequenceNo {
    set {
      DaApiWrapperPINVOKE.CFutureRtnOrderField_SequenceNo_set(swigCPtr, value);
    } 
    get {
      int ret = DaApiWrapperPINVOKE.CFutureRtnOrderField_SequenceNo_get(swigCPtr);
      return ret;
    } 
  }

  public string AccountNo {
    set {
      DaApiWrapperPINVOKE.CFutureRtnOrderField_AccountNo_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRtnOrderField_AccountNo_get(swigCPtr);
      return ret;
    } 
  }

  public string PositionType {
    set {
      DaApiWrapperPINVOKE.CFutureRtnOrderField_PositionType_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRtnOrderField_PositionType_get(swigCPtr);
      return ret;
    } 
  }

  public double LongPosMargin {
    set {
      DaApiWrapperPINVOKE.CFutureRtnOrderField_LongPosMargin_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CFutureRtnOrderField_LongPosMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double ShortPosMargin {
    set {
      DaApiWrapperPINVOKE.CFutureRtnOrderField_ShortPosMargin_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CFutureRtnOrderField_ShortPosMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double CurrPrice {
    set {
      DaApiWrapperPINVOKE.CFutureRtnOrderField_CurrPrice_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CFutureRtnOrderField_CurrPrice_get(swigCPtr);
      return ret;
    } 
  }

  public double ProfitLoss {
    set {
      DaApiWrapperPINVOKE.CFutureRtnOrderField_ProfitLoss_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CFutureRtnOrderField_ProfitLoss_get(swigCPtr);
      return ret;
    } 
  }

  public CFutureRtnOrderField() : this(DaApiWrapperPINVOKE.new_CFutureRtnOrderField(), true) {
  }

}

}
