//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace DAApi.Net {

public class CFutureRspTradeField : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CFutureRspTradeField(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CFutureRspTradeField obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CFutureRspTradeField obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~CFutureRspTradeField() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          DaApiWrapperPINVOKE.delete_CFutureRspTradeField(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string UserId {
    set {
      DaApiWrapperPINVOKE.CFutureRspTradeField_UserId_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspTradeField_UserId_get(swigCPtr);
      return ret;
    } 
  }

  public string AccountNo {
    set {
      DaApiWrapperPINVOKE.CFutureRspTradeField_AccountNo_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspTradeField_AccountNo_get(swigCPtr);
      return ret;
    } 
  }

  public string FilledNo {
    set {
      DaApiWrapperPINVOKE.CFutureRspTradeField_FilledNo_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspTradeField_FilledNo_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderNo {
    set {
      DaApiWrapperPINVOKE.CFutureRspTradeField_OrderNo_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspTradeField_OrderNo_get(swigCPtr);
      return ret;
    } 
  }

  public string SystemNo {
    set {
      DaApiWrapperPINVOKE.CFutureRspTradeField_SystemNo_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspTradeField_SystemNo_get(swigCPtr);
      return ret;
    } 
  }

  public string LocalNo {
    set {
      DaApiWrapperPINVOKE.CFutureRspTradeField_LocalNo_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspTradeField_LocalNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeCode {
    set {
      DaApiWrapperPINVOKE.CFutureRspTradeField_ExchangeCode_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspTradeField_ExchangeCode_get(swigCPtr);
      return ret;
    } 
  }

  public string TreatyCode {
    set {
      DaApiWrapperPINVOKE.CFutureRspTradeField_TreatyCode_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspTradeField_TreatyCode_get(swigCPtr);
      return ret;
    } 
  }

  public string BuySale {
    set {
      DaApiWrapperPINVOKE.CFutureRspTradeField_BuySale_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspTradeField_BuySale_get(swigCPtr);
      return ret;
    } 
  }

  public string FilledNumber {
    set {
      DaApiWrapperPINVOKE.CFutureRspTradeField_FilledNumber_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspTradeField_FilledNumber_get(swigCPtr);
      return ret;
    } 
  }

  public string FilledPrice {
    set {
      DaApiWrapperPINVOKE.CFutureRspTradeField_FilledPrice_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspTradeField_FilledPrice_get(swigCPtr);
      return ret;
    } 
  }

  public string FilledDate {
    set {
      DaApiWrapperPINVOKE.CFutureRspTradeField_FilledDate_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspTradeField_FilledDate_get(swigCPtr);
      return ret;
    } 
  }

  public string FilledTime {
    set {
      DaApiWrapperPINVOKE.CFutureRspTradeField_FilledTime_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspTradeField_FilledTime_get(swigCPtr);
      return ret;
    } 
  }

  public string Commsion {
    set {
      DaApiWrapperPINVOKE.CFutureRspTradeField_Commsion_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspTradeField_Commsion_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderNumber {
    set {
      DaApiWrapperPINVOKE.CFutureRspTradeField_OrderNumber_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspTradeField_OrderNumber_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderPrice {
    set {
      DaApiWrapperPINVOKE.CFutureRspTradeField_OrderPrice_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspTradeField_OrderPrice_get(swigCPtr);
      return ret;
    } 
  }

  public string DeliveryDate {
    set {
      DaApiWrapperPINVOKE.CFutureRspTradeField_DeliveryDate_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspTradeField_DeliveryDate_get(swigCPtr);
      return ret;
    } 
  }

  public string FilledType {
    set {
      DaApiWrapperPINVOKE.CFutureRspTradeField_FilledType_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspTradeField_FilledType_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderType {
    set {
      DaApiWrapperPINVOKE.CFutureRspTradeField_OrderType_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspTradeField_OrderType_get(swigCPtr);
      return ret;
    } 
  }

  public string ValidDate {
    set {
      DaApiWrapperPINVOKE.CFutureRspTradeField_ValidDate_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspTradeField_ValidDate_get(swigCPtr);
      return ret;
    } 
  }

  public string AddReduce {
    set {
      DaApiWrapperPINVOKE.CFutureRspTradeField_AddReduce_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspTradeField_AddReduce_get(swigCPtr);
      return ret;
    } 
  }

  public string ErrorDescription {
    set {
      DaApiWrapperPINVOKE.CFutureRspTradeField_ErrorDescription_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspTradeField_ErrorDescription_get(swigCPtr);
      return ret;
    } 
  }

  public CFutureRspTradeField() : this(DaApiWrapperPINVOKE.new_CFutureRspTradeField(), true) {
  }

}

}
