//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace DAApi.Net {

public class CFutureRspStrategyDetailField : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CFutureRspStrategyDetailField(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CFutureRspStrategyDetailField obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CFutureRspStrategyDetailField obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~CFutureRspStrategyDetailField() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          DaApiWrapperPINVOKE.delete_CFutureRspStrategyDetailField(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string StartegyCommodityNo {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyDetailField_StartegyCommodityNo_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspStrategyDetailField_StartegyCommodityNo_get(swigCPtr);
      return ret;
    } 
  }

  public string StartegyContractNo {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyDetailField_StartegyContractNo_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspStrategyDetailField_StartegyContractNo_get(swigCPtr);
      return ret;
    } 
  }

  public string Price {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyDetailField_Price_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspStrategyDetailField_Price_get(swigCPtr);
      return ret;
    } 
  }

  public int LegNum {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyDetailField_LegNum_set(swigCPtr, value);
    } 
    get {
      int ret = DaApiWrapperPINVOKE.CFutureRspStrategyDetailField_LegNum_get(swigCPtr);
      return ret;
    } 
  }

  public string LastTradeDate {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyDetailField_LastTradeDate_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspStrategyDetailField_LastTradeDate_get(swigCPtr);
      return ret;
    } 
  }

  public int SeqId {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyDetailField_SeqId_set(swigCPtr, value);
    } 
    get {
      int ret = DaApiWrapperPINVOKE.CFutureRspStrategyDetailField_SeqId_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityNo {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyDetailField_CommodityNo_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspStrategyDetailField_CommodityNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ContractNo {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyDetailField_ContractNo_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspStrategyDetailField_ContractNo_get(swigCPtr);
      return ret;
    } 
  }

  public string Direct {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyDetailField_Direct_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspStrategyDetailField_Direct_get(swigCPtr);
      return ret;
    } 
  }

  public int Quantity {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyDetailField_Quantity_set(swigCPtr, value);
    } 
    get {
      int ret = DaApiWrapperPINVOKE.CFutureRspStrategyDetailField_Quantity_get(swigCPtr);
      return ret;
    } 
  }

  public string Model {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyDetailField_Model_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspStrategyDetailField_Model_get(swigCPtr);
      return ret;
    } 
  }

  public string ModifyDate {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyDetailField_ModifyDate_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspStrategyDetailField_ModifyDate_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderMethod {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyDetailField_OrderMethod_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspStrategyDetailField_OrderMethod_get(swigCPtr);
      return ret;
    } 
  }

  public double PriceTolerance {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyDetailField_PriceTolerance_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CFutureRspStrategyDetailField_PriceTolerance_get(swigCPtr);
      return ret;
    } 
  }

  public double PriceParam {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyDetailField_PriceParam_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CFutureRspStrategyDetailField_PriceParam_get(swigCPtr);
      return ret;
    } 
  }

  public int SuportQuantity {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyDetailField_SuportQuantity_set(swigCPtr, value);
    } 
    get {
      int ret = DaApiWrapperPINVOKE.CFutureRspStrategyDetailField_SuportQuantity_get(swigCPtr);
      return ret;
    } 
  }

  public int MinMove {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyDetailField_MinMove_set(swigCPtr, value);
    } 
    get {
      int ret = DaApiWrapperPINVOKE.CFutureRspStrategyDetailField_MinMove_get(swigCPtr);
      return ret;
    } 
  }

  public int TimerOrder {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyDetailField_TimerOrder_set(swigCPtr, value);
    } 
    get {
      int ret = DaApiWrapperPINVOKE.CFutureRspStrategyDetailField_TimerOrder_get(swigCPtr);
      return ret;
    } 
  }

  public string TimerOrderBeyondNum {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyDetailField_TimerOrderBeyondNum_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspStrategyDetailField_TimerOrderBeyondNum_get(swigCPtr);
      return ret;
    } 
  }

  public int TimerOrderPrice {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyDetailField_TimerOrderPrice_set(swigCPtr, value);
    } 
    get {
      int ret = DaApiWrapperPINVOKE.CFutureRspStrategyDetailField_TimerOrderPrice_get(swigCPtr);
      return ret;
    } 
  }

  public string TimerOrderPriceBeyondNum {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyDetailField_TimerOrderPriceBeyondNum_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspStrategyDetailField_TimerOrderPriceBeyondNum_get(swigCPtr);
      return ret;
    } 
  }

  public string TimerOrderPriceTriggerNum {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyDetailField_TimerOrderPriceTriggerNum_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspStrategyDetailField_TimerOrderPriceTriggerNum_get(swigCPtr);
      return ret;
    } 
  }

  public int ZhiSunOrder {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyDetailField_ZhiSunOrder_set(swigCPtr, value);
    } 
    get {
      int ret = DaApiWrapperPINVOKE.CFutureRspStrategyDetailField_ZhiSunOrder_get(swigCPtr);
      return ret;
    } 
  }

  public string ZhiSunOrderBeyondNum {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyDetailField_ZhiSunOrderBeyondNum_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspStrategyDetailField_ZhiSunOrderBeyondNum_get(swigCPtr);
      return ret;
    } 
  }

  public int TimerPingCang {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyDetailField_TimerPingCang_set(swigCPtr, value);
    } 
    get {
      int ret = DaApiWrapperPINVOKE.CFutureRspStrategyDetailField_TimerPingCang_get(swigCPtr);
      return ret;
    } 
  }

  public string TimerPingCangBeyondNum {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyDetailField_TimerPingCangBeyondNum_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspStrategyDetailField_TimerPingCangBeyondNum_get(swigCPtr);
      return ret;
    } 
  }

  public int SafeDeep {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyDetailField_SafeDeep_set(swigCPtr, value);
    } 
    get {
      int ret = DaApiWrapperPINVOKE.CFutureRspStrategyDetailField_SafeDeep_get(swigCPtr);
      return ret;
    } 
  }

  public int MainRange {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyDetailField_MainRange_set(swigCPtr, value);
    } 
    get {
      int ret = DaApiWrapperPINVOKE.CFutureRspStrategyDetailField_MainRange_get(swigCPtr);
      return ret;
    } 
  }

  public CFutureRspStrategyDetailField() : this(DaApiWrapperPINVOKE.new_CFutureRspStrategyDetailField(), true) {
  }

}

}
