//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace DAApi.Net {

public class CFutureRspStrategyField : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CFutureRspStrategyField(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CFutureRspStrategyField obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CFutureRspStrategyField obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~CFutureRspStrategyField() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          DaApiWrapperPINVOKE.delete_CFutureRspStrategyField(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string CommodityCode {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyField_CommodityCode_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspStrategyField_CommodityCode_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeNo {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyField_ExchangeNo_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspStrategyField_ExchangeNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ContractNo {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyField_ContractNo_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspStrategyField_ContractNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ContractFName {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyField_ContractFName_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspStrategyField_ContractFName_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityNo {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyField_CommodityNo_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspStrategyField_CommodityNo_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityFName {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyField_CommodityFName_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspStrategyField_CommodityFName_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityType {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyField_CommodityType_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspStrategyField_CommodityType_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityFCurrencyNo {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyField_CommodityFCurrencyNo_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspStrategyField_CommodityFCurrencyNo_get(swigCPtr);
      return ret;
    } 
  }

  public string CurrencyFName {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyField_CurrencyFName_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspStrategyField_CurrencyFName_get(swigCPtr);
      return ret;
    } 
  }

  public double ProductDot {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyField_ProductDot_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CFutureRspStrategyField_ProductDot_get(swigCPtr);
      return ret;
    } 
  }

  public double UpperTick {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyField_UpperTick_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CFutureRspStrategyField_UpperTick_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeName {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyField_ExchangeName_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspStrategyField_ExchangeName_get(swigCPtr);
      return ret;
    } 
  }

  public double LastSettlePrice {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyField_LastSettlePrice_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CFutureRspStrategyField_LastSettlePrice_get(swigCPtr);
      return ret;
    } 
  }

  public string TradeMonth {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyField_TradeMonth_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspStrategyField_TradeMonth_get(swigCPtr);
      return ret;
    } 
  }

  public int DotNum {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyField_DotNum_set(swigCPtr, value);
    } 
    get {
      int ret = DaApiWrapperPINVOKE.CFutureRspStrategyField_DotNum_get(swigCPtr);
      return ret;
    } 
  }

  public int LowerTick {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyField_LowerTick_set(swigCPtr, value);
    } 
    get {
      int ret = DaApiWrapperPINVOKE.CFutureRspStrategyField_LowerTick_get(swigCPtr);
      return ret;
    } 
  }

  public int DotNumCarry {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyField_DotNumCarry_set(swigCPtr, value);
    } 
    get {
      int ret = DaApiWrapperPINVOKE.CFutureRspStrategyField_DotNumCarry_get(swigCPtr);
      return ret;
    } 
  }

  public double UpperTickCarry {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyField_UpperTickCarry_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CFutureRspStrategyField_UpperTickCarry_get(swigCPtr);
      return ret;
    } 
  }

  public string FirstNoticeDay {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyField_FirstNoticeDay_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspStrategyField_FirstNoticeDay_get(swigCPtr);
      return ret;
    } 
  }

  public double FreezenPercent {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyField_FreezenPercent_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CFutureRspStrategyField_FreezenPercent_get(swigCPtr);
      return ret;
    } 
  }

  public double FreezenMoney {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyField_FreezenMoney_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CFutureRspStrategyField_FreezenMoney_get(swigCPtr);
      return ret;
    } 
  }

  public double FeeMoney {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyField_FeeMoney_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CFutureRspStrategyField_FeeMoney_get(swigCPtr);
      return ret;
    } 
  }

  public double FeePercent {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyField_FeePercent_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CFutureRspStrategyField_FeePercent_get(swigCPtr);
      return ret;
    } 
  }

  public double PriceStrike {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyField_PriceStrike_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CFutureRspStrategyField_PriceStrike_get(swigCPtr);
      return ret;
    } 
  }

  public double ProductDotStrike {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyField_ProductDotStrike_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CFutureRspStrategyField_ProductDotStrike_get(swigCPtr);
      return ret;
    } 
  }

  public double UpperTickStrike {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyField_UpperTickStrike_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CFutureRspStrategyField_UpperTickStrike_get(swigCPtr);
      return ret;
    } 
  }

  public string LastTradeDay {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyField_LastTradeDay_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspStrategyField_LastTradeDay_get(swigCPtr);
      return ret;
    } 
  }

  public string LastUpdateDay {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyField_LastUpdateDay_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspStrategyField_LastUpdateDay_get(swigCPtr);
      return ret;
    } 
  }

  public double CriticalPrice {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyField_CriticalPrice_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CFutureRspStrategyField_CriticalPrice_get(swigCPtr);
      return ret;
    } 
  }

  public double CriticalMinChangedPrice {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyField_CriticalMinChangedPrice_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CFutureRspStrategyField_CriticalMinChangedPrice_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeSub {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyField_ExchangeSub_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspStrategyField_ExchangeSub_get(swigCPtr);
      return ret;
    } 
  }

  public string OptionType {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyField_OptionType_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspStrategyField_OptionType_get(swigCPtr);
      return ret;
    } 
  }

  public string OptionMonth {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyField_OptionMonth_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspStrategyField_OptionMonth_get(swigCPtr);
      return ret;
    } 
  }

  public string OptionStrikePrice {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyField_OptionStrikePrice_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspStrategyField_OptionStrikePrice_get(swigCPtr);
      return ret;
    } 
  }

  public string OptionCommodityNo {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyField_OptionCommodityNo_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspStrategyField_OptionCommodityNo_get(swigCPtr);
      return ret;
    } 
  }

  public string OptionContractNo {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyField_OptionContractNo_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspStrategyField_OptionContractNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ContractFNameEN {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyField_ContractFNameEN_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspStrategyField_ContractFNameEN_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityFNameEN {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyField_CommodityFNameEN_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspStrategyField_CommodityFNameEN_get(swigCPtr);
      return ret;
    } 
  }

  public string OptionStyle {
    set {
      DaApiWrapperPINVOKE.CFutureRspStrategyField_OptionStyle_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspStrategyField_OptionStyle_get(swigCPtr);
      return ret;
    } 
  }

  public CFutureRspStrategyField() : this(DaApiWrapperPINVOKE.new_CFutureRspStrategyField(), true) {
  }

}

}
