//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace DAApi.Net {

public class CFutureRspOrderInsertField : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CFutureRspOrderInsertField(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CFutureRspOrderInsertField obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CFutureRspOrderInsertField obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~CFutureRspOrderInsertField() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          DaApiWrapperPINVOKE.delete_CFutureRspOrderInsertField(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string UserId {
    set {
      DaApiWrapperPINVOKE.CFutureRspOrderInsertField_UserId_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspOrderInsertField_UserId_get(swigCPtr);
      return ret;
    } 
  }

  public string AccountNo {
    set {
      DaApiWrapperPINVOKE.CFutureRspOrderInsertField_AccountNo_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspOrderInsertField_AccountNo_get(swigCPtr);
      return ret;
    } 
  }

  public string SystemNo {
    set {
      DaApiWrapperPINVOKE.CFutureRspOrderInsertField_SystemNo_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspOrderInsertField_SystemNo_get(swigCPtr);
      return ret;
    } 
  }

  public string LocalNo {
    set {
      DaApiWrapperPINVOKE.CFutureRspOrderInsertField_LocalNo_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspOrderInsertField_LocalNo_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderNo {
    set {
      DaApiWrapperPINVOKE.CFutureRspOrderInsertField_OrderNo_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspOrderInsertField_OrderNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeCode {
    set {
      DaApiWrapperPINVOKE.CFutureRspOrderInsertField_ExchangeCode_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspOrderInsertField_ExchangeCode_get(swigCPtr);
      return ret;
    } 
  }

  public string ContractCode {
    set {
      DaApiWrapperPINVOKE.CFutureRspOrderInsertField_ContractCode_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspOrderInsertField_ContractCode_get(swigCPtr);
      return ret;
    } 
  }

  public string BidAskFlag {
    set {
      DaApiWrapperPINVOKE.CFutureRspOrderInsertField_BidAskFlag_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspOrderInsertField_BidAskFlag_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderQty {
    set {
      DaApiWrapperPINVOKE.CFutureRspOrderInsertField_OrderQty_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspOrderInsertField_OrderQty_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderPrice {
    set {
      DaApiWrapperPINVOKE.CFutureRspOrderInsertField_OrderPrice_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspOrderInsertField_OrderPrice_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderType {
    set {
      DaApiWrapperPINVOKE.CFutureRspOrderInsertField_OrderType_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspOrderInsertField_OrderType_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderDate {
    set {
      DaApiWrapperPINVOKE.CFutureRspOrderInsertField_OrderDate_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspOrderInsertField_OrderDate_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderTime {
    set {
      DaApiWrapperPINVOKE.CFutureRspOrderInsertField_OrderTime_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspOrderInsertField_OrderTime_get(swigCPtr);
      return ret;
    } 
  }

  public string ErrorCode {
    set {
      DaApiWrapperPINVOKE.CFutureRspOrderInsertField_ErrorCode_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspOrderInsertField_ErrorCode_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderState {
    set {
      DaApiWrapperPINVOKE.CFutureRspOrderInsertField_OrderState_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspOrderInsertField_OrderState_get(swigCPtr);
      return ret;
    } 
  }

  public string TriggerPrice {
    set {
      DaApiWrapperPINVOKE.CFutureRspOrderInsertField_TriggerPrice_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspOrderInsertField_TriggerPrice_get(swigCPtr);
      return ret;
    } 
  }

  public string TIF {
    set {
      DaApiWrapperPINVOKE.CFutureRspOrderInsertField_TIF_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspOrderInsertField_TIF_get(swigCPtr);
      return ret;
    } 
  }

  public string OpenCloseFlag {
    set {
      DaApiWrapperPINVOKE.CFutureRspOrderInsertField_OpenCloseFlag_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspOrderInsertField_OpenCloseFlag_get(swigCPtr);
      return ret;
    } 
  }

  public string StrategyId {
    set {
      DaApiWrapperPINVOKE.CFutureRspOrderInsertField_StrategyId_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspOrderInsertField_StrategyId_get(swigCPtr);
      return ret;
    } 
  }

  public string MaxShow {
    set {
      DaApiWrapperPINVOKE.CFutureRspOrderInsertField_MaxShow_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspOrderInsertField_MaxShow_get(swigCPtr);
      return ret;
    } 
  }

  public string MinQty {
    set {
      DaApiWrapperPINVOKE.CFutureRspOrderInsertField_MinQty_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspOrderInsertField_MinQty_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeTime {
    set {
      DaApiWrapperPINVOKE.CFutureRspOrderInsertField_ExchangeTime_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspOrderInsertField_ExchangeTime_get(swigCPtr);
      return ret;
    } 
  }

  public string OrdSourceType {
    set {
      DaApiWrapperPINVOKE.CFutureRspOrderInsertField_OrdSourceType_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspOrderInsertField_OrdSourceType_get(swigCPtr);
      return ret;
    } 
  }

  public string Tag50 {
    set {
      DaApiWrapperPINVOKE.CFutureRspOrderInsertField_Tag50_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspOrderInsertField_Tag50_get(swigCPtr);
      return ret;
    } 
  }

  public CFutureRspOrderInsertField() : this(DaApiWrapperPINVOKE.new_CFutureRspOrderInsertField(), true) {
  }

}

}
