//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace DAApi.Net {

public class CFutureReqVerifyCodeField : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CFutureReqVerifyCodeField(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CFutureReqVerifyCodeField obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CFutureReqVerifyCodeField obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~CFutureReqVerifyCodeField() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          DaApiWrapperPINVOKE.delete_CFutureReqVerifyCodeField(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string UserId {
    set {
      DaApiWrapperPINVOKE.CFutureReqVerifyCodeField_UserId_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureReqVerifyCodeField_UserId_get(swigCPtr);
      return ret;
    } 
  }

  public string UserPwd {
    set {
      DaApiWrapperPINVOKE.CFutureReqVerifyCodeField_UserPwd_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureReqVerifyCodeField_UserPwd_get(swigCPtr);
      return ret;
    } 
  }

  public string Type {
    set {
      DaApiWrapperPINVOKE.CFutureReqVerifyCodeField_Type_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureReqVerifyCodeField_Type_get(swigCPtr);
      return ret;
    } 
  }

  public string Question {
    set {
      DaApiWrapperPINVOKE.CFutureReqVerifyCodeField_Question_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureReqVerifyCodeField_Question_get(swigCPtr);
      return ret;
    } 
  }

  public string Answer {
    set {
      DaApiWrapperPINVOKE.CFutureReqVerifyCodeField_Answer_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureReqVerifyCodeField_Answer_get(swigCPtr);
      return ret;
    } 
  }

  public string MobileNumber {
    set {
      DaApiWrapperPINVOKE.CFutureReqVerifyCodeField_MobileNumber_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureReqVerifyCodeField_MobileNumber_get(swigCPtr);
      return ret;
    } 
  }

  public string VerifyCode {
    set {
      DaApiWrapperPINVOKE.CFutureReqVerifyCodeField_VerifyCode_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureReqVerifyCodeField_VerifyCode_get(swigCPtr);
      return ret;
    } 
  }

  public string ErrorDescription {
    set {
      DaApiWrapperPINVOKE.CFutureReqVerifyCodeField_ErrorDescription_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureReqVerifyCodeField_ErrorDescription_get(swigCPtr);
      return ret;
    } 
  }

  public CFutureReqVerifyCodeField() : this(DaApiWrapperPINVOKE.new_CFutureReqVerifyCodeField(), true) {
  }

}

}
