//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace DAApi.Net {

public class CFutureReqUserLoginField : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CFutureReqUserLoginField(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CFutureReqUserLoginField obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CFutureReqUserLoginField obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~CFutureReqUserLoginField() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          DaApiWrapperPINVOKE.delete_CFutureReqUserLoginField(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string UserId {
    set {
      DaApiWrapperPINVOKE.CFutureReqUserLoginField_UserId_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureReqUserLoginField_UserId_get(swigCPtr);
      return ret;
    } 
  }

  public string UserPwd {
    set {
      DaApiWrapperPINVOKE.CFutureReqUserLoginField_UserPwd_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureReqUserLoginField_UserPwd_get(swigCPtr);
      return ret;
    } 
  }

  public string UserType {
    set {
      DaApiWrapperPINVOKE.CFutureReqUserLoginField_UserType_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureReqUserLoginField_UserType_get(swigCPtr);
      return ret;
    } 
  }

  public string MacAddress {
    set {
      DaApiWrapperPINVOKE.CFutureReqUserLoginField_MacAddress_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureReqUserLoginField_MacAddress_get(swigCPtr);
      return ret;
    } 
  }

  public string ComputerName {
    set {
      DaApiWrapperPINVOKE.CFutureReqUserLoginField_ComputerName_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureReqUserLoginField_ComputerName_get(swigCPtr);
      return ret;
    } 
  }

  public string SoftwareName {
    set {
      DaApiWrapperPINVOKE.CFutureReqUserLoginField_SoftwareName_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureReqUserLoginField_SoftwareName_get(swigCPtr);
      return ret;
    } 
  }

  public string SoftwareVersion {
    set {
      DaApiWrapperPINVOKE.CFutureReqUserLoginField_SoftwareVersion_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureReqUserLoginField_SoftwareVersion_get(swigCPtr);
      return ret;
    } 
  }

  public string AuthorCode {
    set {
      DaApiWrapperPINVOKE.CFutureReqUserLoginField_AuthorCode_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureReqUserLoginField_AuthorCode_get(swigCPtr);
      return ret;
    } 
  }

  public string ErrorDescription {
    set {
      DaApiWrapperPINVOKE.CFutureReqUserLoginField_ErrorDescription_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureReqUserLoginField_ErrorDescription_get(swigCPtr);
      return ret;
    } 
  }

  public CFutureReqUserLoginField() : this(DaApiWrapperPINVOKE.new_CFutureReqUserLoginField(), true) {
  }

}

}
