//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace DAApi.Net {

public class CFutureRspCurrencyField : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CFutureRspCurrencyField(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CFutureRspCurrencyField obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CFutureRspCurrencyField obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~CFutureRspCurrencyField() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          DaApiWrapperPINVOKE.delete_CFutureRspCurrencyField(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string CurrencyNo {
    set {
      DaApiWrapperPINVOKE.CFutureRspCurrencyField_CurrencyNo_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspCurrencyField_CurrencyNo_get(swigCPtr);
      return ret;
    } 
  }

  public int IsBase {
    set {
      DaApiWrapperPINVOKE.CFutureRspCurrencyField_IsBase_set(swigCPtr, value);
    } 
    get {
      int ret = DaApiWrapperPINVOKE.CFutureRspCurrencyField_IsBase_get(swigCPtr);
      return ret;
    } 
  }

  public double ChangeRate {
    set {
      DaApiWrapperPINVOKE.CFutureRspCurrencyField_ChangeRate_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CFutureRspCurrencyField_ChangeRate_get(swigCPtr);
      return ret;
    } 
  }

  public string CurrencyName {
    set {
      DaApiWrapperPINVOKE.CFutureRspCurrencyField_CurrencyName_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspCurrencyField_CurrencyName_get(swigCPtr);
      return ret;
    } 
  }

  public string CurrencyNameEN {
    set {
      DaApiWrapperPINVOKE.CFutureRspCurrencyField_CurrencyNameEN_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspCurrencyField_CurrencyNameEN_get(swigCPtr);
      return ret;
    } 
  }

  public CFutureRspCurrencyField() : this(DaApiWrapperPINVOKE.new_CFutureRspCurrencyField(), true) {
  }

}

}
