//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace DAApi.Net {

public class CFutureRspInstrumentField : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CFutureRspInstrumentField(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CFutureRspInstrumentField obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CFutureRspInstrumentField obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~CFutureRspInstrumentField() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          DaApiWrapperPINVOKE.delete_CFutureRspInstrumentField(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string CommodityCode {
    set {
      DaApiWrapperPINVOKE.CFutureRspInstrumentField_CommodityCode_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspInstrumentField_CommodityCode_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeNo {
    set {
      DaApiWrapperPINVOKE.CFutureRspInstrumentField_ExchangeNo_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspInstrumentField_ExchangeNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ContractNo {
    set {
      DaApiWrapperPINVOKE.CFutureRspInstrumentField_ContractNo_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspInstrumentField_ContractNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ContractFName {
    set {
      DaApiWrapperPINVOKE.CFutureRspInstrumentField_ContractFName_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspInstrumentField_ContractFName_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityNo {
    set {
      DaApiWrapperPINVOKE.CFutureRspInstrumentField_CommodityNo_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspInstrumentField_CommodityNo_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityFName {
    set {
      DaApiWrapperPINVOKE.CFutureRspInstrumentField_CommodityFName_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspInstrumentField_CommodityFName_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityType {
    set {
      DaApiWrapperPINVOKE.CFutureRspInstrumentField_CommodityType_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspInstrumentField_CommodityType_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityFCurrencyNo {
    set {
      DaApiWrapperPINVOKE.CFutureRspInstrumentField_CommodityFCurrencyNo_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspInstrumentField_CommodityFCurrencyNo_get(swigCPtr);
      return ret;
    } 
  }

  public string CurrencyFName {
    set {
      DaApiWrapperPINVOKE.CFutureRspInstrumentField_CurrencyFName_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspInstrumentField_CurrencyFName_get(swigCPtr);
      return ret;
    } 
  }

  public double ProductDot {
    set {
      DaApiWrapperPINVOKE.CFutureRspInstrumentField_ProductDot_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CFutureRspInstrumentField_ProductDot_get(swigCPtr);
      return ret;
    } 
  }

  public double UpperTick {
    set {
      DaApiWrapperPINVOKE.CFutureRspInstrumentField_UpperTick_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CFutureRspInstrumentField_UpperTick_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeName {
    set {
      DaApiWrapperPINVOKE.CFutureRspInstrumentField_ExchangeName_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspInstrumentField_ExchangeName_get(swigCPtr);
      return ret;
    } 
  }

  public double LastSettlePrice {
    set {
      DaApiWrapperPINVOKE.CFutureRspInstrumentField_LastSettlePrice_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CFutureRspInstrumentField_LastSettlePrice_get(swigCPtr);
      return ret;
    } 
  }

  public string TradeMonth {
    set {
      DaApiWrapperPINVOKE.CFutureRspInstrumentField_TradeMonth_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspInstrumentField_TradeMonth_get(swigCPtr);
      return ret;
    } 
  }

  public int DotNum {
    set {
      DaApiWrapperPINVOKE.CFutureRspInstrumentField_DotNum_set(swigCPtr, value);
    } 
    get {
      int ret = DaApiWrapperPINVOKE.CFutureRspInstrumentField_DotNum_get(swigCPtr);
      return ret;
    } 
  }

  public int LowerTick {
    set {
      DaApiWrapperPINVOKE.CFutureRspInstrumentField_LowerTick_set(swigCPtr, value);
    } 
    get {
      int ret = DaApiWrapperPINVOKE.CFutureRspInstrumentField_LowerTick_get(swigCPtr);
      return ret;
    } 
  }

  public int DotNumCarry {
    set {
      DaApiWrapperPINVOKE.CFutureRspInstrumentField_DotNumCarry_set(swigCPtr, value);
    } 
    get {
      int ret = DaApiWrapperPINVOKE.CFutureRspInstrumentField_DotNumCarry_get(swigCPtr);
      return ret;
    } 
  }

  public double UpperTickCarry {
    set {
      DaApiWrapperPINVOKE.CFutureRspInstrumentField_UpperTickCarry_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CFutureRspInstrumentField_UpperTickCarry_get(swigCPtr);
      return ret;
    } 
  }

  public string FirstNoticeDay {
    set {
      DaApiWrapperPINVOKE.CFutureRspInstrumentField_FirstNoticeDay_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspInstrumentField_FirstNoticeDay_get(swigCPtr);
      return ret;
    } 
  }

  public double FreezenPercent {
    set {
      DaApiWrapperPINVOKE.CFutureRspInstrumentField_FreezenPercent_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CFutureRspInstrumentField_FreezenPercent_get(swigCPtr);
      return ret;
    } 
  }

  public double FreezenMoney {
    set {
      DaApiWrapperPINVOKE.CFutureRspInstrumentField_FreezenMoney_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CFutureRspInstrumentField_FreezenMoney_get(swigCPtr);
      return ret;
    } 
  }

  public double FeeMoney {
    set {
      DaApiWrapperPINVOKE.CFutureRspInstrumentField_FeeMoney_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CFutureRspInstrumentField_FeeMoney_get(swigCPtr);
      return ret;
    } 
  }

  public double FeePercent {
    set {
      DaApiWrapperPINVOKE.CFutureRspInstrumentField_FeePercent_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CFutureRspInstrumentField_FeePercent_get(swigCPtr);
      return ret;
    } 
  }

  public double PriceStrike {
    set {
      DaApiWrapperPINVOKE.CFutureRspInstrumentField_PriceStrike_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CFutureRspInstrumentField_PriceStrike_get(swigCPtr);
      return ret;
    } 
  }

  public double ProductDotStrike {
    set {
      DaApiWrapperPINVOKE.CFutureRspInstrumentField_ProductDotStrike_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CFutureRspInstrumentField_ProductDotStrike_get(swigCPtr);
      return ret;
    } 
  }

  public double UpperTickStrike {
    set {
      DaApiWrapperPINVOKE.CFutureRspInstrumentField_UpperTickStrike_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CFutureRspInstrumentField_UpperTickStrike_get(swigCPtr);
      return ret;
    } 
  }

  public string LastTradeDay {
    set {
      DaApiWrapperPINVOKE.CFutureRspInstrumentField_LastTradeDay_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspInstrumentField_LastTradeDay_get(swigCPtr);
      return ret;
    } 
  }

  public string LastUpdateDay {
    set {
      DaApiWrapperPINVOKE.CFutureRspInstrumentField_LastUpdateDay_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspInstrumentField_LastUpdateDay_get(swigCPtr);
      return ret;
    } 
  }

  public double CriticalPrice {
    set {
      DaApiWrapperPINVOKE.CFutureRspInstrumentField_CriticalPrice_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CFutureRspInstrumentField_CriticalPrice_get(swigCPtr);
      return ret;
    } 
  }

  public double CriticalMinChangedPrice {
    set {
      DaApiWrapperPINVOKE.CFutureRspInstrumentField_CriticalMinChangedPrice_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CFutureRspInstrumentField_CriticalMinChangedPrice_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeSub {
    set {
      DaApiWrapperPINVOKE.CFutureRspInstrumentField_ExchangeSub_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspInstrumentField_ExchangeSub_get(swigCPtr);
      return ret;
    } 
  }

  public string OptionType {
    set {
      DaApiWrapperPINVOKE.CFutureRspInstrumentField_OptionType_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspInstrumentField_OptionType_get(swigCPtr);
      return ret;
    } 
  }

  public string OptionMonth {
    set {
      DaApiWrapperPINVOKE.CFutureRspInstrumentField_OptionMonth_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspInstrumentField_OptionMonth_get(swigCPtr);
      return ret;
    } 
  }

  public string OptionStrikePrice {
    set {
      DaApiWrapperPINVOKE.CFutureRspInstrumentField_OptionStrikePrice_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspInstrumentField_OptionStrikePrice_get(swigCPtr);
      return ret;
    } 
  }

  public string OptionCommodityNo {
    set {
      DaApiWrapperPINVOKE.CFutureRspInstrumentField_OptionCommodityNo_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspInstrumentField_OptionCommodityNo_get(swigCPtr);
      return ret;
    } 
  }

  public string OptionContractNo {
    set {
      DaApiWrapperPINVOKE.CFutureRspInstrumentField_OptionContractNo_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspInstrumentField_OptionContractNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ContractFNameEN {
    set {
      DaApiWrapperPINVOKE.CFutureRspInstrumentField_ContractFNameEN_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspInstrumentField_ContractFNameEN_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityFNameEN {
    set {
      DaApiWrapperPINVOKE.CFutureRspInstrumentField_CommodityFNameEN_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspInstrumentField_CommodityFNameEN_get(swigCPtr);
      return ret;
    } 
  }

  public string OptionStyle {
    set {
      DaApiWrapperPINVOKE.CFutureRspInstrumentField_OptionStyle_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspInstrumentField_OptionStyle_get(swigCPtr);
      return ret;
    } 
  }

  public CFutureRspInstrumentField() : this(DaApiWrapperPINVOKE.new_CFutureRspInstrumentField(), true) {
  }

}

}
