//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace DAApi.Net {

public class CFutureRspCommodityTimeField : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CFutureRspCommodityTimeField(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CFutureRspCommodityTimeField obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CFutureRspCommodityTimeField obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~CFutureRspCommodityTimeField() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          DaApiWrapperPINVOKE.delete_CFutureRspCommodityTimeField(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string CrossTrade {
    set {
      DaApiWrapperPINVOKE.CFutureRspCommodityTimeField_CrossTrade_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspCommodityTimeField_CrossTrade_get(swigCPtr);
      return ret;
    } 
  }

  public string Stage {
    set {
      DaApiWrapperPINVOKE.CFutureRspCommodityTimeField_Stage_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspCommodityTimeField_Stage_get(swigCPtr);
      return ret;
    } 
  }

  public string Summer {
    set {
      DaApiWrapperPINVOKE.CFutureRspCommodityTimeField_Summer_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspCommodityTimeField_Summer_get(swigCPtr);
      return ret;
    } 
  }

  public string Opendate {
    set {
      DaApiWrapperPINVOKE.CFutureRspCommodityTimeField_Opendate_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspCommodityTimeField_Opendate_get(swigCPtr);
      return ret;
    } 
  }

  public string Closingdate {
    set {
      DaApiWrapperPINVOKE.CFutureRspCommodityTimeField_Closingdate_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspCommodityTimeField_Closingdate_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityNo {
    set {
      DaApiWrapperPINVOKE.CFutureRspCommodityTimeField_CommodityNo_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspCommodityTimeField_CommodityNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ComName {
    set {
      DaApiWrapperPINVOKE.CFutureRspCommodityTimeField_ComName_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspCommodityTimeField_ComName_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeNo {
    set {
      DaApiWrapperPINVOKE.CFutureRspCommodityTimeField_ExchangeNo_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspCommodityTimeField_ExchangeNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ExName {
    set {
      DaApiWrapperPINVOKE.CFutureRspCommodityTimeField_ExName_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CFutureRspCommodityTimeField_ExName_get(swigCPtr);
      return ret;
    } 
  }

  public CFutureRspCommodityTimeField() : this(DaApiWrapperPINVOKE.new_CFutureRspCommodityTimeField(), true) {
  }

}

}
