//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace DAApi.Net {

public class CMarketReqMarketDataField : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CMarketReqMarketDataField(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CMarketReqMarketDataField obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CMarketReqMarketDataField obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~CMarketReqMarketDataField() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          DaApiWrapperPINVOKE.delete_CMarketReqMarketDataField(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public char MarketType {
    set {
      DaApiWrapperPINVOKE.CMarketReqMarketDataField_MarketType_set(swigCPtr, value);
    } 
    get {
      char ret = DaApiWrapperPINVOKE.CMarketReqMarketDataField_MarketType_get(swigCPtr);
      return ret;
    } 
  }

  public char SubscMode {
    set {
      DaApiWrapperPINVOKE.CMarketReqMarketDataField_SubscMode_set(swigCPtr, value);
    } 
    get {
      char ret = DaApiWrapperPINVOKE.CMarketReqMarketDataField_SubscMode_get(swigCPtr);
      return ret;
    } 
  }

  public int MarketCount {
    set {
      DaApiWrapperPINVOKE.CMarketReqMarketDataField_MarketCount_set(swigCPtr, value);
    } 
    get {
      int ret = DaApiWrapperPINVOKE.CMarketReqMarketDataField_MarketCount_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_a_256__char MarketTrcode {
    set {
      DaApiWrapperPINVOKE.CMarketReqMarketDataField_MarketTrcode_set(swigCPtr, SWIGTYPE_p_a_256__char.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = DaApiWrapperPINVOKE.CMarketReqMarketDataField_MarketTrcode_get(swigCPtr);
      SWIGTYPE_p_a_256__char ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_a_256__char(cPtr, false);
      return ret;
    } 
  }

  public string ErrorDescription {
    set {
      DaApiWrapperPINVOKE.CMarketReqMarketDataField_ErrorDescription_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CMarketReqMarketDataField_ErrorDescription_get(swigCPtr);
      return ret;
    } 
  }

  public CMarketReqMarketDataField() : this(DaApiWrapperPINVOKE.new_CMarketReqMarketDataField(), true) {
  }

}

}
