//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace DAApi.Net {

public class CStockRspOrderInsertField : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CStockRspOrderInsertField(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CStockRspOrderInsertField obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CStockRspOrderInsertField obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~CStockRspOrderInsertField() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          DaApiWrapperPINVOKE.delete_CStockRspOrderInsertField(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string UserId {
    set {
      DaApiWrapperPINVOKE.CStockRspOrderInsertField_UserId_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspOrderInsertField_UserId_get(swigCPtr);
      return ret;
    } 
  }

  public string AccountNo {
    set {
      DaApiWrapperPINVOKE.CStockRspOrderInsertField_AccountNo_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspOrderInsertField_AccountNo_get(swigCPtr);
      return ret;
    } 
  }

  public string SystemNo {
    set {
      DaApiWrapperPINVOKE.CStockRspOrderInsertField_SystemNo_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspOrderInsertField_SystemNo_get(swigCPtr);
      return ret;
    } 
  }

  public string LocalNo {
    set {
      DaApiWrapperPINVOKE.CStockRspOrderInsertField_LocalNo_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspOrderInsertField_LocalNo_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderNo {
    set {
      DaApiWrapperPINVOKE.CStockRspOrderInsertField_OrderNo_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspOrderInsertField_OrderNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeCode {
    set {
      DaApiWrapperPINVOKE.CStockRspOrderInsertField_ExchangeCode_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspOrderInsertField_ExchangeCode_get(swigCPtr);
      return ret;
    } 
  }

  public string ContractCode {
    set {
      DaApiWrapperPINVOKE.CStockRspOrderInsertField_ContractCode_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspOrderInsertField_ContractCode_get(swigCPtr);
      return ret;
    } 
  }

  public string BidAskFlag {
    set {
      DaApiWrapperPINVOKE.CStockRspOrderInsertField_BidAskFlag_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspOrderInsertField_BidAskFlag_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderQty {
    set {
      DaApiWrapperPINVOKE.CStockRspOrderInsertField_OrderQty_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspOrderInsertField_OrderQty_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderPrice {
    set {
      DaApiWrapperPINVOKE.CStockRspOrderInsertField_OrderPrice_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspOrderInsertField_OrderPrice_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderType {
    set {
      DaApiWrapperPINVOKE.CStockRspOrderInsertField_OrderType_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspOrderInsertField_OrderType_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderDate {
    set {
      DaApiWrapperPINVOKE.CStockRspOrderInsertField_OrderDate_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspOrderInsertField_OrderDate_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderTime {
    set {
      DaApiWrapperPINVOKE.CStockRspOrderInsertField_OrderTime_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspOrderInsertField_OrderTime_get(swigCPtr);
      return ret;
    } 
  }

  public string ErrorCode {
    set {
      DaApiWrapperPINVOKE.CStockRspOrderInsertField_ErrorCode_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspOrderInsertField_ErrorCode_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderState {
    set {
      DaApiWrapperPINVOKE.CStockRspOrderInsertField_OrderState_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspOrderInsertField_OrderState_get(swigCPtr);
      return ret;
    } 
  }

  public string TriggerPrice {
    set {
      DaApiWrapperPINVOKE.CStockRspOrderInsertField_TriggerPrice_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspOrderInsertField_TriggerPrice_get(swigCPtr);
      return ret;
    } 
  }

  public string TIF {
    set {
      DaApiWrapperPINVOKE.CStockRspOrderInsertField_TIF_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspOrderInsertField_TIF_get(swigCPtr);
      return ret;
    } 
  }

  public string OpenCloseFlag {
    set {
      DaApiWrapperPINVOKE.CStockRspOrderInsertField_OpenCloseFlag_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspOrderInsertField_OpenCloseFlag_get(swigCPtr);
      return ret;
    } 
  }

  public string StrategyId {
    set {
      DaApiWrapperPINVOKE.CStockRspOrderInsertField_StrategyId_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspOrderInsertField_StrategyId_get(swigCPtr);
      return ret;
    } 
  }

  public string MaxShow {
    set {
      DaApiWrapperPINVOKE.CStockRspOrderInsertField_MaxShow_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspOrderInsertField_MaxShow_get(swigCPtr);
      return ret;
    } 
  }

  public string MinQty {
    set {
      DaApiWrapperPINVOKE.CStockRspOrderInsertField_MinQty_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspOrderInsertField_MinQty_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeTime {
    set {
      DaApiWrapperPINVOKE.CStockRspOrderInsertField_ExchangeTime_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspOrderInsertField_ExchangeTime_get(swigCPtr);
      return ret;
    } 
  }

  public CStockRspOrderInsertField() : this(DaApiWrapperPINVOKE.new_CStockRspOrderInsertField(), true) {
  }

}

}
