//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace DAApi.Net {

public class CStockReqSafeVerifyField : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CStockReqSafeVerifyField(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CStockReqSafeVerifyField obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CStockReqSafeVerifyField obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~CStockReqSafeVerifyField() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          DaApiWrapperPINVOKE.delete_CStockReqSafeVerifyField(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string UserId {
    set {
      DaApiWrapperPINVOKE.CStockReqSafeVerifyField_UserId_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockReqSafeVerifyField_UserId_get(swigCPtr);
      return ret;
    } 
  }

  public string UserPwd {
    set {
      DaApiWrapperPINVOKE.CStockReqSafeVerifyField_UserPwd_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockReqSafeVerifyField_UserPwd_get(swigCPtr);
      return ret;
    } 
  }

  public string Type {
    set {
      DaApiWrapperPINVOKE.CStockReqSafeVerifyField_Type_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockReqSafeVerifyField_Type_get(swigCPtr);
      return ret;
    } 
  }

  public string Question {
    set {
      DaApiWrapperPINVOKE.CStockReqSafeVerifyField_Question_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockReqSafeVerifyField_Question_get(swigCPtr);
      return ret;
    } 
  }

  public string Answer {
    set {
      DaApiWrapperPINVOKE.CStockReqSafeVerifyField_Answer_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockReqSafeVerifyField_Answer_get(swigCPtr);
      return ret;
    } 
  }

  public string MobileNumber {
    set {
      DaApiWrapperPINVOKE.CStockReqSafeVerifyField_MobileNumber_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockReqSafeVerifyField_MobileNumber_get(swigCPtr);
      return ret;
    } 
  }

  public string VerifyCode {
    set {
      DaApiWrapperPINVOKE.CStockReqSafeVerifyField_VerifyCode_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockReqSafeVerifyField_VerifyCode_get(swigCPtr);
      return ret;
    } 
  }

  public string SaveMac {
    set {
      DaApiWrapperPINVOKE.CStockReqSafeVerifyField_SaveMac_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockReqSafeVerifyField_SaveMac_get(swigCPtr);
      return ret;
    } 
  }

  public string MacAddress {
    set {
      DaApiWrapperPINVOKE.CStockReqSafeVerifyField_MacAddress_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockReqSafeVerifyField_MacAddress_get(swigCPtr);
      return ret;
    } 
  }

  public string ErrorDescription {
    set {
      DaApiWrapperPINVOKE.CStockReqSafeVerifyField_ErrorDescription_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockReqSafeVerifyField_ErrorDescription_get(swigCPtr);
      return ret;
    } 
  }

  public CStockReqSafeVerifyField() : this(DaApiWrapperPINVOKE.new_CStockReqSafeVerifyField(), true) {
  }

}

}
