//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace DAApi.Net {

public class CStockReqOrderInsertField : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CStockReqOrderInsertField(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CStockReqOrderInsertField obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CStockReqOrderInsertField obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~CStockReqOrderInsertField() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          DaApiWrapperPINVOKE.delete_CStockReqOrderInsertField(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string UserId {
    set {
      DaApiWrapperPINVOKE.CStockReqOrderInsertField_UserId_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockReqOrderInsertField_UserId_get(swigCPtr);
      return ret;
    } 
  }

  public string AccountNo {
    set {
      DaApiWrapperPINVOKE.CStockReqOrderInsertField_AccountNo_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockReqOrderInsertField_AccountNo_get(swigCPtr);
      return ret;
    } 
  }

  public string LocalNo {
    set {
      DaApiWrapperPINVOKE.CStockReqOrderInsertField_LocalNo_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockReqOrderInsertField_LocalNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeCode {
    set {
      DaApiWrapperPINVOKE.CStockReqOrderInsertField_ExchangeCode_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockReqOrderInsertField_ExchangeCode_get(swigCPtr);
      return ret;
    } 
  }

  public string ContractCode {
    set {
      DaApiWrapperPINVOKE.CStockReqOrderInsertField_ContractCode_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockReqOrderInsertField_ContractCode_get(swigCPtr);
      return ret;
    } 
  }

  public string BidAskFlag {
    set {
      DaApiWrapperPINVOKE.CStockReqOrderInsertField_BidAskFlag_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockReqOrderInsertField_BidAskFlag_get(swigCPtr);
      return ret;
    } 
  }

  public string OpenCloseFlag {
    set {
      DaApiWrapperPINVOKE.CStockReqOrderInsertField_OpenCloseFlag_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockReqOrderInsertField_OpenCloseFlag_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderQty {
    set {
      DaApiWrapperPINVOKE.CStockReqOrderInsertField_OrderQty_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockReqOrderInsertField_OrderQty_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderPrice {
    set {
      DaApiWrapperPINVOKE.CStockReqOrderInsertField_OrderPrice_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockReqOrderInsertField_OrderPrice_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderType {
    set {
      DaApiWrapperPINVOKE.CStockReqOrderInsertField_OrderType_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockReqOrderInsertField_OrderType_get(swigCPtr);
      return ret;
    } 
  }

  public string TriggerPrice {
    set {
      DaApiWrapperPINVOKE.CStockReqOrderInsertField_TriggerPrice_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockReqOrderInsertField_TriggerPrice_get(swigCPtr);
      return ret;
    } 
  }

  public string TIF {
    set {
      DaApiWrapperPINVOKE.CStockReqOrderInsertField_TIF_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockReqOrderInsertField_TIF_get(swigCPtr);
      return ret;
    } 
  }

  public string StrategyId {
    set {
      DaApiWrapperPINVOKE.CStockReqOrderInsertField_StrategyId_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockReqOrderInsertField_StrategyId_get(swigCPtr);
      return ret;
    } 
  }

  public string MaxShow {
    set {
      DaApiWrapperPINVOKE.CStockReqOrderInsertField_MaxShow_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockReqOrderInsertField_MaxShow_get(swigCPtr);
      return ret;
    } 
  }

  public string MinQty {
    set {
      DaApiWrapperPINVOKE.CStockReqOrderInsertField_MinQty_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockReqOrderInsertField_MinQty_get(swigCPtr);
      return ret;
    } 
  }

  public string ErrorDescription {
    set {
      DaApiWrapperPINVOKE.CStockReqOrderInsertField_ErrorDescription_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockReqOrderInsertField_ErrorDescription_get(swigCPtr);
      return ret;
    } 
  }

  public CStockReqOrderInsertField() : this(DaApiWrapperPINVOKE.new_CStockReqOrderInsertField(), true) {
  }

}

}
