//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace DAApi.Net {

public class CStockRspCapitalField : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CStockRspCapitalField(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CStockRspCapitalField obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CStockRspCapitalField obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~CStockRspCapitalField() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          DaApiWrapperPINVOKE.delete_CStockRspCapitalField(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string UserId {
    set {
      DaApiWrapperPINVOKE.CStockRspCapitalField_UserId_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspCapitalField_UserId_get(swigCPtr);
      return ret;
    } 
  }

  public string Deposit {
    set {
      DaApiWrapperPINVOKE.CStockRspCapitalField_Deposit_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspCapitalField_Deposit_get(swigCPtr);
      return ret;
    } 
  }

  public string Withdraw {
    set {
      DaApiWrapperPINVOKE.CStockRspCapitalField_Withdraw_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspCapitalField_Withdraw_get(swigCPtr);
      return ret;
    } 
  }

  public string TodayTradableFund {
    set {
      DaApiWrapperPINVOKE.CStockRspCapitalField_TodayTradableFund_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspCapitalField_TodayTradableFund_get(swigCPtr);
      return ret;
    } 
  }

  public string TodayInitialBalance {
    set {
      DaApiWrapperPINVOKE.CStockRspCapitalField_TodayInitialBalance_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspCapitalField_TodayInitialBalance_get(swigCPtr);
      return ret;
    } 
  }

  public string TodayRealtimeBalance {
    set {
      DaApiWrapperPINVOKE.CStockRspCapitalField_TodayRealtimeBalance_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspCapitalField_TodayRealtimeBalance_get(swigCPtr);
      return ret;
    } 
  }

  public string FrozenFund {
    set {
      DaApiWrapperPINVOKE.CStockRspCapitalField_FrozenFund_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspCapitalField_FrozenFund_get(swigCPtr);
      return ret;
    } 
  }

  public string Commission {
    set {
      DaApiWrapperPINVOKE.CStockRspCapitalField_Commission_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspCapitalField_Commission_get(swigCPtr);
      return ret;
    } 
  }

  public string InitialMargin {
    set {
      DaApiWrapperPINVOKE.CStockRspCapitalField_InitialMargin_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspCapitalField_InitialMargin_get(swigCPtr);
      return ret;
    } 
  }

  public string YdTradableFund {
    set {
      DaApiWrapperPINVOKE.CStockRspCapitalField_YdTradableFund_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspCapitalField_YdTradableFund_get(swigCPtr);
      return ret;
    } 
  }

  public string YdInitialBalance {
    set {
      DaApiWrapperPINVOKE.CStockRspCapitalField_YdInitialBalance_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspCapitalField_YdInitialBalance_get(swigCPtr);
      return ret;
    } 
  }

  public string YdFinalBalance {
    set {
      DaApiWrapperPINVOKE.CStockRspCapitalField_YdFinalBalance_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspCapitalField_YdFinalBalance_get(swigCPtr);
      return ret;
    } 
  }

  public string ProfitLoss {
    set {
      DaApiWrapperPINVOKE.CStockRspCapitalField_ProfitLoss_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspCapitalField_ProfitLoss_get(swigCPtr);
      return ret;
    } 
  }

  public string CurrencyNo {
    set {
      DaApiWrapperPINVOKE.CStockRspCapitalField_CurrencyNo_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspCapitalField_CurrencyNo_get(swigCPtr);
      return ret;
    } 
  }

  public double CurrencyRate {
    set {
      DaApiWrapperPINVOKE.CStockRspCapitalField_CurrencyRate_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CStockRspCapitalField_CurrencyRate_get(swigCPtr);
      return ret;
    } 
  }

  public double LMEUnexpiredPL {
    set {
      DaApiWrapperPINVOKE.CStockRspCapitalField_LMEUnexpiredPL_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CStockRspCapitalField_LMEUnexpiredPL_get(swigCPtr);
      return ret;
    } 
  }

  public double LMEUnaccountPL {
    set {
      DaApiWrapperPINVOKE.CStockRspCapitalField_LMEUnaccountPL_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CStockRspCapitalField_LMEUnaccountPL_get(swigCPtr);
      return ret;
    } 
  }

  public double MaintenanceMargin {
    set {
      DaApiWrapperPINVOKE.CStockRspCapitalField_MaintenanceMargin_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CStockRspCapitalField_MaintenanceMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double Premium {
    set {
      DaApiWrapperPINVOKE.CStockRspCapitalField_Premium_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CStockRspCapitalField_Premium_get(swigCPtr);
      return ret;
    } 
  }

  public double CreditAmount {
    set {
      DaApiWrapperPINVOKE.CStockRspCapitalField_CreditAmount_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CStockRspCapitalField_CreditAmount_get(swigCPtr);
      return ret;
    } 
  }

  public double IntialFund {
    set {
      DaApiWrapperPINVOKE.CStockRspCapitalField_IntialFund_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CStockRspCapitalField_IntialFund_get(swigCPtr);
      return ret;
    } 
  }

  public string FundAccountNo {
    set {
      DaApiWrapperPINVOKE.CStockRspCapitalField_FundAccountNo_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspCapitalField_FundAccountNo_get(swigCPtr);
      return ret;
    } 
  }

  public double MortgageInMoney {
    set {
      DaApiWrapperPINVOKE.CStockRspCapitalField_MortgageInMoney_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CStockRspCapitalField_MortgageInMoney_get(swigCPtr);
      return ret;
    } 
  }

  public double MarginLimit {
    set {
      DaApiWrapperPINVOKE.CStockRspCapitalField_MarginLimit_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CStockRspCapitalField_MarginLimit_get(swigCPtr);
      return ret;
    } 
  }

  public double BorrowInMoney {
    set {
      DaApiWrapperPINVOKE.CStockRspCapitalField_BorrowInMoney_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CStockRspCapitalField_BorrowInMoney_get(swigCPtr);
      return ret;
    } 
  }

  public double T1DeliveryMoney {
    set {
      DaApiWrapperPINVOKE.CStockRspCapitalField_T1DeliveryMoney_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CStockRspCapitalField_T1DeliveryMoney_get(swigCPtr);
      return ret;
    } 
  }

  public double T2DeliveryMoney {
    set {
      DaApiWrapperPINVOKE.CStockRspCapitalField_T2DeliveryMoney_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CStockRspCapitalField_T2DeliveryMoney_get(swigCPtr);
      return ret;
    } 
  }

  public double T3DeliveryMoney {
    set {
      DaApiWrapperPINVOKE.CStockRspCapitalField_T3DeliveryMoney_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CStockRspCapitalField_T3DeliveryMoney_get(swigCPtr);
      return ret;
    } 
  }

  public double TNDeliveryMoney {
    set {
      DaApiWrapperPINVOKE.CStockRspCapitalField_TNDeliveryMoney_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CStockRspCapitalField_TNDeliveryMoney_get(swigCPtr);
      return ret;
    } 
  }

  public double TradeLimit {
    set {
      DaApiWrapperPINVOKE.CStockRspCapitalField_TradeLimit_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CStockRspCapitalField_TradeLimit_get(swigCPtr);
      return ret;
    } 
  }

  public double CanCashOutMoneyAmount {
    set {
      DaApiWrapperPINVOKE.CStockRspCapitalField_CanCashOutMoneyAmount_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CStockRspCapitalField_CanCashOutMoneyAmount_get(swigCPtr);
      return ret;
    } 
  }

  public double DepositInterest {
    set {
      DaApiWrapperPINVOKE.CStockRspCapitalField_DepositInterest_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CStockRspCapitalField_DepositInterest_get(swigCPtr);
      return ret;
    } 
  }

  public double LoanInterest {
    set {
      DaApiWrapperPINVOKE.CStockRspCapitalField_LoanInterest_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CStockRspCapitalField_LoanInterest_get(swigCPtr);
      return ret;
    } 
  }

  public double CrossCurrencyMaxMoneyAmt {
    set {
      DaApiWrapperPINVOKE.CStockRspCapitalField_CrossCurrencyMaxMoneyAmt_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CStockRspCapitalField_CrossCurrencyMaxMoneyAmt_get(swigCPtr);
      return ret;
    } 
  }

  public double SellShortFrozenMoney {
    set {
      DaApiWrapperPINVOKE.CStockRspCapitalField_SellShortFrozenMoney_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CStockRspCapitalField_SellShortFrozenMoney_get(swigCPtr);
      return ret;
    } 
  }

  public double SellShortInterest {
    set {
      DaApiWrapperPINVOKE.CStockRspCapitalField_SellShortInterest_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CStockRspCapitalField_SellShortInterest_get(swigCPtr);
      return ret;
    } 
  }

  public double ShortPosAddtionalMargin {
    set {
      DaApiWrapperPINVOKE.CStockRspCapitalField_ShortPosAddtionalMargin_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CStockRspCapitalField_ShortPosAddtionalMargin_get(swigCPtr);
      return ret;
    } 
  }

  public string ErrorDescription {
    set {
      DaApiWrapperPINVOKE.CStockRspCapitalField_ErrorDescription_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspCapitalField_ErrorDescription_get(swigCPtr);
      return ret;
    } 
  }

  public CStockRspCapitalField() : this(DaApiWrapperPINVOKE.new_CStockRspCapitalField(), true) {
  }

}

}
