//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace DAApi.Net {

public class CStockRtnOrderField : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CStockRtnOrderField(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CStockRtnOrderField obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CStockRtnOrderField obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~CStockRtnOrderField() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          DaApiWrapperPINVOKE.delete_CStockRtnOrderField(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string LocalOrderNo {
    set {
      DaApiWrapperPINVOKE.CStockRtnOrderField_LocalOrderNo_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRtnOrderField_LocalOrderNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeNo {
    set {
      DaApiWrapperPINVOKE.CStockRtnOrderField_ExchangeNo_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRtnOrderField_ExchangeNo_get(swigCPtr);
      return ret;
    } 
  }

  public string TreatyCode {
    set {
      DaApiWrapperPINVOKE.CStockRtnOrderField_TreatyCode_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRtnOrderField_TreatyCode_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderNo {
    set {
      DaApiWrapperPINVOKE.CStockRtnOrderField_OrderNo_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRtnOrderField_OrderNo_get(swigCPtr);
      return ret;
    } 
  }

  public int OrderNumber {
    set {
      DaApiWrapperPINVOKE.CStockRtnOrderField_OrderNumber_set(swigCPtr, value);
    } 
    get {
      int ret = DaApiWrapperPINVOKE.CStockRtnOrderField_OrderNumber_get(swigCPtr);
      return ret;
    } 
  }

  public int FilledNumber {
    set {
      DaApiWrapperPINVOKE.CStockRtnOrderField_FilledNumber_set(swigCPtr, value);
    } 
    get {
      int ret = DaApiWrapperPINVOKE.CStockRtnOrderField_FilledNumber_get(swigCPtr);
      return ret;
    } 
  }

  public double FilledAdvPrice {
    set {
      DaApiWrapperPINVOKE.CStockRtnOrderField_FilledAdvPrice_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CStockRtnOrderField_FilledAdvPrice_get(swigCPtr);
      return ret;
    } 
  }

  public int BuyHoldNumber {
    set {
      DaApiWrapperPINVOKE.CStockRtnOrderField_BuyHoldNumber_set(swigCPtr, value);
    } 
    get {
      int ret = DaApiWrapperPINVOKE.CStockRtnOrderField_BuyHoldNumber_get(swigCPtr);
      return ret;
    } 
  }

  public double BuyHoldOpenPrice {
    set {
      DaApiWrapperPINVOKE.CStockRtnOrderField_BuyHoldOpenPrice_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CStockRtnOrderField_BuyHoldOpenPrice_get(swigCPtr);
      return ret;
    } 
  }

  public double BuyHoldPrice {
    set {
      DaApiWrapperPINVOKE.CStockRtnOrderField_BuyHoldPrice_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CStockRtnOrderField_BuyHoldPrice_get(swigCPtr);
      return ret;
    } 
  }

  public int SaleHoldNumber {
    set {
      DaApiWrapperPINVOKE.CStockRtnOrderField_SaleHoldNumber_set(swigCPtr, value);
    } 
    get {
      int ret = DaApiWrapperPINVOKE.CStockRtnOrderField_SaleHoldNumber_get(swigCPtr);
      return ret;
    } 
  }

  public double SaleHoldOpenPrice {
    set {
      DaApiWrapperPINVOKE.CStockRtnOrderField_SaleHoldOpenPrice_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CStockRtnOrderField_SaleHoldOpenPrice_get(swigCPtr);
      return ret;
    } 
  }

  public double SaleHoldPrice {
    set {
      DaApiWrapperPINVOKE.CStockRtnOrderField_SaleHoldPrice_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CStockRtnOrderField_SaleHoldPrice_get(swigCPtr);
      return ret;
    } 
  }

  public string IsCanceled {
    set {
      DaApiWrapperPINVOKE.CStockRtnOrderField_IsCanceled_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRtnOrderField_IsCanceled_get(swigCPtr);
      return ret;
    } 
  }

  public double FilledTotalFee {
    set {
      DaApiWrapperPINVOKE.CStockRtnOrderField_FilledTotalFee_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CStockRtnOrderField_FilledTotalFee_get(swigCPtr);
      return ret;
    } 
  }

  public int Status {
    set {
      DaApiWrapperPINVOKE.CStockRtnOrderField_Status_set(swigCPtr, value);
    } 
    get {
      int ret = DaApiWrapperPINVOKE.CStockRtnOrderField_Status_get(swigCPtr);
      return ret;
    } 
  }

  public string AccountNo {
    set {
      DaApiWrapperPINVOKE.CStockRtnOrderField_AccountNo_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRtnOrderField_AccountNo_get(swigCPtr);
      return ret;
    } 
  }

  public string HoldType {
    set {
      DaApiWrapperPINVOKE.CStockRtnOrderField_HoldType_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRtnOrderField_HoldType_get(swigCPtr);
      return ret;
    } 
  }

  public double HoldMarginBuy {
    set {
      DaApiWrapperPINVOKE.CStockRtnOrderField_HoldMarginBuy_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CStockRtnOrderField_HoldMarginBuy_get(swigCPtr);
      return ret;
    } 
  }

  public double HoldMarginSale {
    set {
      DaApiWrapperPINVOKE.CStockRtnOrderField_HoldMarginSale_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CStockRtnOrderField_HoldMarginSale_get(swigCPtr);
      return ret;
    } 
  }

  public double CurrPrice {
    set {
      DaApiWrapperPINVOKE.CStockRtnOrderField_CurrPrice_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CStockRtnOrderField_CurrPrice_get(swigCPtr);
      return ret;
    } 
  }

  public double FloatProfit {
    set {
      DaApiWrapperPINVOKE.CStockRtnOrderField_FloatProfit_set(swigCPtr, value);
    } 
    get {
      double ret = DaApiWrapperPINVOKE.CStockRtnOrderField_FloatProfit_get(swigCPtr);
      return ret;
    } 
  }

  public CStockRtnOrderField() : this(DaApiWrapperPINVOKE.new_CStockRtnOrderField(), true) {
  }

}

}
