//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace DAApi.Net {

public class CStockRspAccountField : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CStockRspAccountField(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CStockRspAccountField obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CStockRspAccountField obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~CStockRspAccountField() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          DaApiWrapperPINVOKE.delete_CStockRspAccountField(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string UserId {
    set {
      DaApiWrapperPINVOKE.CStockRspAccountField_UserId_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspAccountField_UserId_get(swigCPtr);
      return ret;
    } 
  }

  public string UserName {
    set {
      DaApiWrapperPINVOKE.CStockRspAccountField_UserName_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspAccountField_UserName_get(swigCPtr);
      return ret;
    } 
  }

  public string UserType {
    set {
      DaApiWrapperPINVOKE.CStockRspAccountField_UserType_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspAccountField_UserType_get(swigCPtr);
      return ret;
    } 
  }

  public string LoginPwd {
    set {
      DaApiWrapperPINVOKE.CStockRspAccountField_LoginPwd_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspAccountField_LoginPwd_get(swigCPtr);
      return ret;
    } 
  }

  public string AccountNo {
    set {
      DaApiWrapperPINVOKE.CStockRspAccountField_AccountNo_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspAccountField_AccountNo_get(swigCPtr);
      return ret;
    } 
  }

  public string TradePwd {
    set {
      DaApiWrapperPINVOKE.CStockRspAccountField_TradePwd_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspAccountField_TradePwd_get(swigCPtr);
      return ret;
    } 
  }

  public string IsSimulation {
    set {
      DaApiWrapperPINVOKE.CStockRspAccountField_IsSimulation_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspAccountField_IsSimulation_get(swigCPtr);
      return ret;
    } 
  }

  public string FrontendIp {
    set {
      DaApiWrapperPINVOKE.CStockRspAccountField_FrontendIp_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspAccountField_FrontendIp_get(swigCPtr);
      return ret;
    } 
  }

  public string FrontendPort {
    set {
      DaApiWrapperPINVOKE.CStockRspAccountField_FrontendPort_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspAccountField_FrontendPort_get(swigCPtr);
      return ret;
    } 
  }

  public string CurrencyNo {
    set {
      DaApiWrapperPINVOKE.CStockRspAccountField_CurrencyNo_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspAccountField_CurrencyNo_get(swigCPtr);
      return ret;
    } 
  }

  public string UserState {
    set {
      DaApiWrapperPINVOKE.CStockRspAccountField_UserState_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspAccountField_UserState_get(swigCPtr);
      return ret;
    } 
  }

  public string SelAll {
    set {
      DaApiWrapperPINVOKE.CStockRspAccountField_SelAll_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspAccountField_SelAll_get(swigCPtr);
      return ret;
    } 
  }

  public string Strategy {
    set {
      DaApiWrapperPINVOKE.CStockRspAccountField_Strategy_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspAccountField_Strategy_get(swigCPtr);
      return ret;
    } 
  }

  public string Inner {
    set {
      DaApiWrapperPINVOKE.CStockRspAccountField_Inner_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspAccountField_Inner_get(swigCPtr);
      return ret;
    } 
  }

  public string YingSun {
    set {
      DaApiWrapperPINVOKE.CStockRspAccountField_YingSun_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspAccountField_YingSun_get(swigCPtr);
      return ret;
    } 
  }

  public string ChaoDan {
    set {
      DaApiWrapperPINVOKE.CStockRspAccountField_ChaoDan_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspAccountField_ChaoDan_get(swigCPtr);
      return ret;
    } 
  }

  public string Option {
    set {
      DaApiWrapperPINVOKE.CStockRspAccountField_Option_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspAccountField_Option_get(swigCPtr);
      return ret;
    } 
  }

  public string CmeMarket {
    set {
      DaApiWrapperPINVOKE.CStockRspAccountField_CmeMarket_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspAccountField_CmeMarket_get(swigCPtr);
      return ret;
    } 
  }

  public string CmeCOMEXMarket {
    set {
      DaApiWrapperPINVOKE.CStockRspAccountField_CmeCOMEXMarket_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspAccountField_CmeCOMEXMarket_get(swigCPtr);
      return ret;
    } 
  }

  public string CmeNYMEXMarket {
    set {
      DaApiWrapperPINVOKE.CStockRspAccountField_CmeNYMEXMarket_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspAccountField_CmeNYMEXMarket_get(swigCPtr);
      return ret;
    } 
  }

  public string CmeCBTMarket {
    set {
      DaApiWrapperPINVOKE.CStockRspAccountField_CmeCBTMarket_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspAccountField_CmeCBTMarket_get(swigCPtr);
      return ret;
    } 
  }

  public string IceUSMarket {
    set {
      DaApiWrapperPINVOKE.CStockRspAccountField_IceUSMarket_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspAccountField_IceUSMarket_get(swigCPtr);
      return ret;
    } 
  }

  public string IceECMarket {
    set {
      DaApiWrapperPINVOKE.CStockRspAccountField_IceECMarket_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspAccountField_IceECMarket_get(swigCPtr);
      return ret;
    } 
  }

  public string IceEFMarket {
    set {
      DaApiWrapperPINVOKE.CStockRspAccountField_IceEFMarket_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspAccountField_IceEFMarket_get(swigCPtr);
      return ret;
    } 
  }

  public string CanTradeStockHK {
    set {
      DaApiWrapperPINVOKE.CStockRspAccountField_CanTradeStockHK_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspAccountField_CanTradeStockHK_get(swigCPtr);
      return ret;
    } 
  }

  public string CanTradeStockAM {
    set {
      DaApiWrapperPINVOKE.CStockRspAccountField_CanTradeStockAM_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspAccountField_CanTradeStockAM_get(swigCPtr);
      return ret;
    } 
  }

  public string MultiLogin {
    set {
      DaApiWrapperPINVOKE.CStockRspAccountField_MultiLogin_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspAccountField_MultiLogin_get(swigCPtr);
      return ret;
    } 
  }

  public string SellStockHK {
    set {
      DaApiWrapperPINVOKE.CStockRspAccountField_SellStockHK_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspAccountField_SellStockHK_get(swigCPtr);
      return ret;
    } 
  }

  public string SellStockAM {
    set {
      DaApiWrapperPINVOKE.CStockRspAccountField_SellStockAM_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspAccountField_SellStockAM_get(swigCPtr);
      return ret;
    } 
  }

  public string CanTradeStockKRX {
    set {
      DaApiWrapperPINVOKE.CStockRspAccountField_CanTradeStockKRX_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspAccountField_CanTradeStockKRX_get(swigCPtr);
      return ret;
    } 
  }

  public string HkexMarket {
    set {
      DaApiWrapperPINVOKE.CStockRspAccountField_HkexMarket_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspAccountField_HkexMarket_get(swigCPtr);
      return ret;
    } 
  }

  public string IdNumber {
    set {
      DaApiWrapperPINVOKE.CStockRspAccountField_IdNumber_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspAccountField_IdNumber_get(swigCPtr);
      return ret;
    } 
  }

  public string HkexMarketFee {
    set {
      DaApiWrapperPINVOKE.CStockRspAccountField_HkexMarketFee_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspAccountField_HkexMarketFee_get(swigCPtr);
      return ret;
    } 
  }

  public string IsProfessional {
    set {
      DaApiWrapperPINVOKE.CStockRspAccountField_IsProfessional_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspAccountField_IsProfessional_get(swigCPtr);
      return ret;
    } 
  }

  public string IsOverSea {
    set {
      DaApiWrapperPINVOKE.CStockRspAccountField_IsOverSea_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspAccountField_IsOverSea_get(swigCPtr);
      return ret;
    } 
  }

  public string IsFirstLogin {
    set {
      DaApiWrapperPINVOKE.CStockRspAccountField_IsFirstLogin_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspAccountField_IsFirstLogin_get(swigCPtr);
      return ret;
    } 
  }

  public string UserMobile {
    set {
      DaApiWrapperPINVOKE.CStockRspAccountField_UserMobile_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspAccountField_UserMobile_get(swigCPtr);
      return ret;
    } 
  }

  public string HasSetQA {
    set {
      DaApiWrapperPINVOKE.CStockRspAccountField_HasSetQA_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspAccountField_HasSetQA_get(swigCPtr);
      return ret;
    } 
  }

  public string CanTradeStockSGXQ {
    set {
      DaApiWrapperPINVOKE.CStockRspAccountField_CanTradeStockSGXQ_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspAccountField_CanTradeStockSGXQ_get(swigCPtr);
      return ret;
    } 
  }

  public string ExistMac {
    set {
      DaApiWrapperPINVOKE.CStockRspAccountField_ExistMac_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspAccountField_ExistMac_get(swigCPtr);
      return ret;
    } 
  }

  public string RatioINE {
    set {
      DaApiWrapperPINVOKE.CStockRspAccountField_RatioINE_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspAccountField_RatioINE_get(swigCPtr);
      return ret;
    } 
  }

  public string EurexMarket {
    set {
      DaApiWrapperPINVOKE.CStockRspAccountField_EurexMarket_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspAccountField_EurexMarket_get(swigCPtr);
      return ret;
    } 
  }

  public string HkexIsOverMaxTerminal {
    set {
      DaApiWrapperPINVOKE.CStockRspAccountField_HkexIsOverMaxTerminal_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspAccountField_HkexIsOverMaxTerminal_get(swigCPtr);
      return ret;
    } 
  }

  public string HkexOverMoney {
    set {
      DaApiWrapperPINVOKE.CStockRspAccountField_HkexOverMoney_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspAccountField_HkexOverMoney_get(swigCPtr);
      return ret;
    } 
  }

  public string CanTradeStockAU {
    set {
      DaApiWrapperPINVOKE.CStockRspAccountField_CanTradeStockAU_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspAccountField_CanTradeStockAU_get(swigCPtr);
      return ret;
    } 
  }

  public string NyFlag {
    set {
      DaApiWrapperPINVOKE.CStockRspAccountField_NyFlag_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspAccountField_NyFlag_get(swigCPtr);
      return ret;
    } 
  }

  public CStockRspAccountField() : this(DaApiWrapperPINVOKE.new_CStockRspAccountField(), true) {
  }

}

}
