//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace DAApi.Net {

public class CStockRspOrderField : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CStockRspOrderField(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CStockRspOrderField obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CStockRspOrderField obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~CStockRspOrderField() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          DaApiWrapperPINVOKE.delete_CStockRspOrderField(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string UserId {
    set {
      DaApiWrapperPINVOKE.CStockRspOrderField_UserId_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspOrderField_UserId_get(swigCPtr);
      return ret;
    } 
  }

  public string AccountNo {
    set {
      DaApiWrapperPINVOKE.CStockRspOrderField_AccountNo_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspOrderField_AccountNo_get(swigCPtr);
      return ret;
    } 
  }

  public string SystemNo {
    set {
      DaApiWrapperPINVOKE.CStockRspOrderField_SystemNo_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspOrderField_SystemNo_get(swigCPtr);
      return ret;
    } 
  }

  public string LocalNo {
    set {
      DaApiWrapperPINVOKE.CStockRspOrderField_LocalNo_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspOrderField_LocalNo_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderNo {
    set {
      DaApiWrapperPINVOKE.CStockRspOrderField_OrderNo_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspOrderField_OrderNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeCode {
    set {
      DaApiWrapperPINVOKE.CStockRspOrderField_ExchangeCode_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspOrderField_ExchangeCode_get(swigCPtr);
      return ret;
    } 
  }

  public string ContractCode {
    set {
      DaApiWrapperPINVOKE.CStockRspOrderField_ContractCode_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspOrderField_ContractCode_get(swigCPtr);
      return ret;
    } 
  }

  public string BidAskFlag {
    set {
      DaApiWrapperPINVOKE.CStockRspOrderField_BidAskFlag_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspOrderField_BidAskFlag_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderQty {
    set {
      DaApiWrapperPINVOKE.CStockRspOrderField_OrderQty_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspOrderField_OrderQty_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderPrice {
    set {
      DaApiWrapperPINVOKE.CStockRspOrderField_OrderPrice_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspOrderField_OrderPrice_get(swigCPtr);
      return ret;
    } 
  }

  public string FilledQty {
    set {
      DaApiWrapperPINVOKE.CStockRspOrderField_FilledQty_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspOrderField_FilledQty_get(swigCPtr);
      return ret;
    } 
  }

  public string FilledPrice {
    set {
      DaApiWrapperPINVOKE.CStockRspOrderField_FilledPrice_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspOrderField_FilledPrice_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderType {
    set {
      DaApiWrapperPINVOKE.CStockRspOrderField_OrderType_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspOrderField_OrderType_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderDate {
    set {
      DaApiWrapperPINVOKE.CStockRspOrderField_OrderDate_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspOrderField_OrderDate_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderTime {
    set {
      DaApiWrapperPINVOKE.CStockRspOrderField_OrderTime_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspOrderField_OrderTime_get(swigCPtr);
      return ret;
    } 
  }

  public string ErrorCode {
    set {
      DaApiWrapperPINVOKE.CStockRspOrderField_ErrorCode_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspOrderField_ErrorCode_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderState {
    set {
      DaApiWrapperPINVOKE.CStockRspOrderField_OrderState_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspOrderField_OrderState_get(swigCPtr);
      return ret;
    } 
  }

  public string CancelUserId {
    set {
      DaApiWrapperPINVOKE.CStockRspOrderField_CancelUserId_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspOrderField_CancelUserId_get(swigCPtr);
      return ret;
    } 
  }

  public string TriggerPrice {
    set {
      DaApiWrapperPINVOKE.CStockRspOrderField_TriggerPrice_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspOrderField_TriggerPrice_get(swigCPtr);
      return ret;
    } 
  }

  public string TIF {
    set {
      DaApiWrapperPINVOKE.CStockRspOrderField_TIF_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspOrderField_TIF_get(swigCPtr);
      return ret;
    } 
  }

  public string OpenCloseFlag {
    set {
      DaApiWrapperPINVOKE.CStockRspOrderField_OpenCloseFlag_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspOrderField_OpenCloseFlag_get(swigCPtr);
      return ret;
    } 
  }

  public string StrategyId {
    set {
      DaApiWrapperPINVOKE.CStockRspOrderField_StrategyId_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspOrderField_StrategyId_get(swigCPtr);
      return ret;
    } 
  }

  public string MaxShow {
    set {
      DaApiWrapperPINVOKE.CStockRspOrderField_MaxShow_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspOrderField_MaxShow_get(swigCPtr);
      return ret;
    } 
  }

  public string MinQty {
    set {
      DaApiWrapperPINVOKE.CStockRspOrderField_MinQty_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspOrderField_MinQty_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeTime {
    set {
      DaApiWrapperPINVOKE.CStockRspOrderField_ExchangeTime_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspOrderField_ExchangeTime_get(swigCPtr);
      return ret;
    } 
  }

  public string CancelTime {
    set {
      DaApiWrapperPINVOKE.CStockRspOrderField_CancelTime_set(swigCPtr, value);
    } 
    get {
      string ret = DaApiWrapperPINVOKE.CStockRspOrderField_CancelTime_get(swigCPtr);
      return ret;
    } 
  }

  public CStockRspOrderField() : this(DaApiWrapperPINVOKE.new_CStockRspOrderField(), true) {
  }

}

}
