//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace DAApi.Net {

public class DaApiWrapper {
  public static readonly int DA_STR_SIZE = DaApiWrapperPINVOKE.DA_STR_SIZE_get();
  public static readonly int TRADE_MAX_NUM_ONE_PAGE = DaApiWrapperPINVOKE.TRADE_MAX_NUM_ONE_PAGE_get();
  public static readonly int MAX_BROKER = DaApiWrapperPINVOKE.MAX_BROKER_get();
  public static readonly string DAAPI_VERSION = DaApiWrapperPINVOKE.DAAPI_VERSION_get();
  public static readonly int MAX_SUB_COUNT = DaApiWrapperPINVOKE.MAX_SUB_COUNT_get();
  public static readonly char DAF_TYPE_Stock = DaApiWrapperPINVOKE.DAF_TYPE_Stock_get();
  public static readonly char DAF_TYPE_Future = DaApiWrapperPINVOKE.DAF_TYPE_Future_get();
  public static readonly int DAF_TYPE_Unknown = DaApiWrapperPINVOKE.DAF_TYPE_Unknown_get();
  public static readonly char DAF_SUB_Append = DaApiWrapperPINVOKE.DAF_SUB_Append_get();
  public static readonly char DAF_SUB_Replace = DaApiWrapperPINVOKE.DAF_SUB_Replace_get();
  public static readonly char DAF_SUB_Unsubcribe = DaApiWrapperPINVOKE.DAF_SUB_Unsubcribe_get();
  public static readonly char DAF_SUB_UnsubcribeAll = DaApiWrapperPINVOKE.DAF_SUB_UnsubcribeAll_get();
  public static readonly char DAF_Market_Full = DaApiWrapperPINVOKE.DAF_Market_Full_get();
  public static readonly char DAF_Market_Fill = DaApiWrapperPINVOKE.DAF_Market_Fill_get();
  public static readonly string EMPTY_STRING = DaApiWrapperPINVOKE.EMPTY_STRING_get();
  public static readonly string DERIVATIVE_BID = DaApiWrapperPINVOKE.DERIVATIVE_BID_get();
  public static readonly string DERIVATIVE_ASK = DaApiWrapperPINVOKE.DERIVATIVE_ASK_get();
  public static readonly string DERIVATIVE_OPEN_POS_FLAG = DaApiWrapperPINVOKE.DERIVATIVE_OPEN_POS_FLAG_get();
  public static readonly string DERIVATIVE_CLOSE_POS_FLAG = DaApiWrapperPINVOKE.DERIVATIVE_CLOSE_POS_FLAG_get();
  public static readonly string DERIVATIVE_LIMIT_ORDER = DaApiWrapperPINVOKE.DERIVATIVE_LIMIT_ORDER_get();
  public static readonly string DERIVATIVE_MARKET_ORDER = DaApiWrapperPINVOKE.DERIVATIVE_MARKET_ORDER_get();
  public static readonly string DERIVATIVE_LIMIT_STOP_ORDER = DaApiWrapperPINVOKE.DERIVATIVE_LIMIT_STOP_ORDER_get();
  public static readonly string DERIVATIVE_STOP_LOSS_ORDER = DaApiWrapperPINVOKE.DERIVATIVE_STOP_LOSS_ORDER_get();
  public static readonly string DERIVATIVE_TDY_TIF = DaApiWrapperPINVOKE.DERIVATIVE_TDY_TIF_get();
  public static readonly string DERIVATIVE_GTC_TIF = DaApiWrapperPINVOKE.DERIVATIVE_GTC_TIF_get();
  public static readonly string DERIVATIVE_OPG_TIF = DaApiWrapperPINVOKE.DERIVATIVE_OPG_TIF_get();
  public static readonly string DERIVATIVE_IOC_TIF = DaApiWrapperPINVOKE.DERIVATIVE_IOC_TIF_get();
  public static readonly string DERIVATIVE_FOK_TIF = DaApiWrapperPINVOKE.DERIVATIVE_FOK_TIF_get();
  public static readonly string DERIVATIVE_GTD_TIF = DaApiWrapperPINVOKE.DERIVATIVE_GTD_TIF_get();
  public static readonly string DERIVATIVE_ATC_TIF = DaApiWrapperPINVOKE.DERIVATIVE_ATC_TIF_get();
  public static readonly string DERIVATIVE_FAK_TIF = DaApiWrapperPINVOKE.DERIVATIVE_FAK_TIF_get();
  public static readonly string DERIVATIVE_ORDER_STATE1 = DaApiWrapperPINVOKE.DERIVATIVE_ORDER_STATE1_get();
  public static readonly string DERIVATIVE_ORDER_STATE2 = DaApiWrapperPINVOKE.DERIVATIVE_ORDER_STATE2_get();
  public static readonly string DERIVATIVE_ORDER_STATE3 = DaApiWrapperPINVOKE.DERIVATIVE_ORDER_STATE3_get();
  public static readonly string DERIVATIVE_ORDER_STATE4 = DaApiWrapperPINVOKE.DERIVATIVE_ORDER_STATE4_get();
  public static readonly string DERIVATIVE_ORDER_STATE5 = DaApiWrapperPINVOKE.DERIVATIVE_ORDER_STATE5_get();
  public static readonly string DERIVATIVE_ORDER_STATE6 = DaApiWrapperPINVOKE.DERIVATIVE_ORDER_STATE6_get();
  public static readonly string DERIVATIVE_ORDER_STATE7 = DaApiWrapperPINVOKE.DERIVATIVE_ORDER_STATE7_get();
  public static readonly string DERIVATIVE_ORDER_STATE8 = DaApiWrapperPINVOKE.DERIVATIVE_ORDER_STATE8_get();
  public static readonly string DERIVATIVE_ORDER_STATE9 = DaApiWrapperPINVOKE.DERIVATIVE_ORDER_STATE9_get();
  public static readonly string DERIVATIVE_ORDER_STATEA = DaApiWrapperPINVOKE.DERIVATIVE_ORDER_STATEA_get();
  public static readonly string DERIVATIVE_IS_SIMULATED_USER = DaApiWrapperPINVOKE.DERIVATIVE_IS_SIMULATED_USER_get();
  public static readonly string DERIVATIVE_IS_NOT_SIMULATED_USER = DaApiWrapperPINVOKE.DERIVATIVE_IS_NOT_SIMULATED_USER_get();
  public static readonly string DERIVATIVE_ORDER_IS_NOT_CANCELLED = DaApiWrapperPINVOKE.DERIVATIVE_ORDER_IS_NOT_CANCELLED_get();
  public static readonly string DERIVATIVE_ORDER_IS_CANCELLED = DaApiWrapperPINVOKE.DERIVATIVE_ORDER_IS_CANCELLED_get();
  public static readonly string DERIVATIVE_POSITION_TYPE_Y = DaApiWrapperPINVOKE.DERIVATIVE_POSITION_TYPE_Y_get();
  public static readonly string DERIVATIVE_POSITION_TYPE_T = DaApiWrapperPINVOKE.DERIVATIVE_POSITION_TYPE_T_get();
  public static readonly string STOCK_POSITION_FLAG_LONG = DaApiWrapperPINVOKE.STOCK_POSITION_FLAG_LONG_get();
  public static readonly string STOCK_POSITION_FLAG_SHORT = DaApiWrapperPINVOKE.STOCK_POSITION_FLAG_SHORT_get();
  public static readonly string STOCK_BID = DaApiWrapperPINVOKE.STOCK_BID_get();
  public static readonly string STOCK_ASK = DaApiWrapperPINVOKE.STOCK_ASK_get();
  public static readonly string STOCK_OPEN_POS_FLAG = DaApiWrapperPINVOKE.STOCK_OPEN_POS_FLAG_get();
  public static readonly string STOCK_CLOSE_POS_FLAG = DaApiWrapperPINVOKE.STOCK_CLOSE_POS_FLAG_get();
  public static readonly string STOCK_LIMIT_ORDER = DaApiWrapperPINVOKE.STOCK_LIMIT_ORDER_get();
  public static readonly string STOCK_MARKET_ORDER = DaApiWrapperPINVOKE.STOCK_MARKET_ORDER_get();
  public static readonly string STOCK_LIMIT_STOP_ORDER = DaApiWrapperPINVOKE.STOCK_LIMIT_STOP_ORDER_get();
  public static readonly string STOCK_STOP_LOSS_ORDER = DaApiWrapperPINVOKE.STOCK_STOP_LOSS_ORDER_get();
  public static readonly string STOCK_TDY_TIF = DaApiWrapperPINVOKE.STOCK_TDY_TIF_get();
  public static readonly string STOCK_GTC_TIF = DaApiWrapperPINVOKE.STOCK_GTC_TIF_get();
  public static readonly string STOCK_OPG_TIF = DaApiWrapperPINVOKE.STOCK_OPG_TIF_get();
  public static readonly string STOCK_IOC_TIF = DaApiWrapperPINVOKE.STOCK_IOC_TIF_get();
  public static readonly string STOCK_FOK_TIF = DaApiWrapperPINVOKE.STOCK_FOK_TIF_get();
  public static readonly string STOCK_GTD_TIF = DaApiWrapperPINVOKE.STOCK_GTD_TIF_get();
  public static readonly string STOCK_ATC_TIF = DaApiWrapperPINVOKE.STOCK_ATC_TIF_get();
  public static readonly string STOCK_FAK_TIF = DaApiWrapperPINVOKE.STOCK_FAK_TIF_get();
  public static readonly string STOCK_ORDER_STATE1 = DaApiWrapperPINVOKE.STOCK_ORDER_STATE1_get();
  public static readonly string STOCK_ORDER_STATE2 = DaApiWrapperPINVOKE.STOCK_ORDER_STATE2_get();
  public static readonly string STOCK_ORDER_STATE3 = DaApiWrapperPINVOKE.STOCK_ORDER_STATE3_get();
  public static readonly string STOCK_ORDER_STATE4 = DaApiWrapperPINVOKE.STOCK_ORDER_STATE4_get();
  public static readonly string STOCK_ORDER_STATE5 = DaApiWrapperPINVOKE.STOCK_ORDER_STATE5_get();
  public static readonly string STOCK_ORDER_STATE6 = DaApiWrapperPINVOKE.STOCK_ORDER_STATE6_get();
  public static readonly string STOCK_ORDER_STATE7 = DaApiWrapperPINVOKE.STOCK_ORDER_STATE7_get();
  public static readonly string STOCK_ORDER_STATE8 = DaApiWrapperPINVOKE.STOCK_ORDER_STATE8_get();
  public static readonly string STOCK_ORDER_STATE9 = DaApiWrapperPINVOKE.STOCK_ORDER_STATE9_get();
  public static readonly string STOCK_ORDER_STATEA = DaApiWrapperPINVOKE.STOCK_ORDER_STATEA_get();
  public static readonly string STOCK_IS_SIMULATED_USER = DaApiWrapperPINVOKE.STOCK_IS_SIMULATED_USER_get();
  public static readonly string STOCK_IS_NOT_SIMULATED_USER = DaApiWrapperPINVOKE.STOCK_IS_NOT_SIMULATED_USER_get();
}

}
