//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace DAApi.Net {

public class IMarketEvent : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal IMarketEvent(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IMarketEvent obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(IMarketEvent obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~IMarketEvent() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          DaApiWrapperPINVOKE.delete_IMarketEvent(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public virtual void OnFrontConnected() {
    if (SwigDerivedClassHasMethod("OnFrontConnected", swigMethodTypes0)) DaApiWrapperPINVOKE.IMarketEvent_OnFrontConnectedSwigExplicitIMarketEvent(swigCPtr); else DaApiWrapperPINVOKE.IMarketEvent_OnFrontConnected(swigCPtr);
  }

  public virtual void OnFrontDisconnected(int iReason) {
    if (SwigDerivedClassHasMethod("OnFrontDisconnected", swigMethodTypes1)) DaApiWrapperPINVOKE.IMarketEvent_OnFrontDisconnectedSwigExplicitIMarketEvent(swigCPtr, iReason); else DaApiWrapperPINVOKE.IMarketEvent_OnFrontDisconnected(swigCPtr, iReason);
  }

  public virtual void OnHeartBeatWarning(int iTimeLapse) {
    if (SwigDerivedClassHasMethod("OnHeartBeatWarning", swigMethodTypes2)) DaApiWrapperPINVOKE.IMarketEvent_OnHeartBeatWarningSwigExplicitIMarketEvent(swigCPtr, iTimeLapse); else DaApiWrapperPINVOKE.IMarketEvent_OnHeartBeatWarning(swigCPtr, iTimeLapse);
  }

  public virtual void OnRspRawData(string rawData) {
    if (SwigDerivedClassHasMethod("OnRspRawData", swigMethodTypes3)) DaApiWrapperPINVOKE.IMarketEvent_OnRspRawDataSwigExplicitIMarketEvent(swigCPtr, rawData); else DaApiWrapperPINVOKE.IMarketEvent_OnRspRawData(swigCPtr, rawData);
  }

  public virtual void OnRspUserLogin(CMarketRspInfoField pRspInfo, int iRequestID, bool bIsLast) {
    if (SwigDerivedClassHasMethod("OnRspUserLogin", swigMethodTypes4)) DaApiWrapperPINVOKE.IMarketEvent_OnRspUserLoginSwigExplicitIMarketEvent(swigCPtr, CMarketRspInfoField.getCPtr(pRspInfo), iRequestID, bIsLast); else DaApiWrapperPINVOKE.IMarketEvent_OnRspUserLogin(swigCPtr, CMarketRspInfoField.getCPtr(pRspInfo), iRequestID, bIsLast);
  }

  public virtual void OnRspTradeDate(CMarketRspTradeDateField pRspTradeDate, CMarketRspInfoField pRspInfo, int iRequestID, bool bIsLast) {
    if (SwigDerivedClassHasMethod("OnRspTradeDate", swigMethodTypes5)) DaApiWrapperPINVOKE.IMarketEvent_OnRspTradeDateSwigExplicitIMarketEvent(swigCPtr, CMarketRspTradeDateField.getCPtr(pRspTradeDate), CMarketRspInfoField.getCPtr(pRspInfo), iRequestID, bIsLast); else DaApiWrapperPINVOKE.IMarketEvent_OnRspTradeDate(swigCPtr, CMarketRspTradeDateField.getCPtr(pRspTradeDate), CMarketRspInfoField.getCPtr(pRspInfo), iRequestID, bIsLast);
  }

  public virtual void OnRspBrokerData(CMarketRspBrokerDataField pRspBrokerData, CMarketRspInfoField pRspInfo, int iRequestID, bool bIsLast) {
    if (SwigDerivedClassHasMethod("OnRspBrokerData", swigMethodTypes6)) DaApiWrapperPINVOKE.IMarketEvent_OnRspBrokerDataSwigExplicitIMarketEvent(swigCPtr, CMarketRspBrokerDataField.getCPtr(pRspBrokerData), CMarketRspInfoField.getCPtr(pRspInfo), iRequestID, bIsLast); else DaApiWrapperPINVOKE.IMarketEvent_OnRspBrokerData(swigCPtr, CMarketRspBrokerDataField.getCPtr(pRspBrokerData), CMarketRspInfoField.getCPtr(pRspInfo), iRequestID, bIsLast);
  }

  public virtual void OnRspMarketData(CMarketRspMarketDataField pRspMarketData, CMarketRspInfoField pRspInfo, int iRequestID, bool bIsLast) {
    if (SwigDerivedClassHasMethod("OnRspMarketData", swigMethodTypes7)) DaApiWrapperPINVOKE.IMarketEvent_OnRspMarketDataSwigExplicitIMarketEvent(swigCPtr, CMarketRspMarketDataField.getCPtr(pRspMarketData), CMarketRspInfoField.getCPtr(pRspInfo), iRequestID, bIsLast); else DaApiWrapperPINVOKE.IMarketEvent_OnRspMarketData(swigCPtr, CMarketRspMarketDataField.getCPtr(pRspMarketData), CMarketRspInfoField.getCPtr(pRspInfo), iRequestID, bIsLast);
  }

  public virtual void OnRspUserLogout(CMarketRspInfoField pRspInfo, int iRequestID, bool bIsLast) {
    if (SwigDerivedClassHasMethod("OnRspUserLogout", swigMethodTypes8)) DaApiWrapperPINVOKE.IMarketEvent_OnRspUserLogoutSwigExplicitIMarketEvent(swigCPtr, CMarketRspInfoField.getCPtr(pRspInfo), iRequestID, bIsLast); else DaApiWrapperPINVOKE.IMarketEvent_OnRspUserLogout(swigCPtr, CMarketRspInfoField.getCPtr(pRspInfo), iRequestID, bIsLast);
  }

  public IMarketEvent() : this(DaApiWrapperPINVOKE.new_IMarketEvent(), true) {
    SwigDirectorConnect();
  }

  private void SwigDirectorConnect() {
    if (SwigDerivedClassHasMethod("OnFrontConnected", swigMethodTypes0))
      swigDelegate0 = new SwigDelegateIMarketEvent_0(SwigDirectorMethodOnFrontConnected);
    if (SwigDerivedClassHasMethod("OnFrontDisconnected", swigMethodTypes1))
      swigDelegate1 = new SwigDelegateIMarketEvent_1(SwigDirectorMethodOnFrontDisconnected);
    if (SwigDerivedClassHasMethod("OnHeartBeatWarning", swigMethodTypes2))
      swigDelegate2 = new SwigDelegateIMarketEvent_2(SwigDirectorMethodOnHeartBeatWarning);
    if (SwigDerivedClassHasMethod("OnRspRawData", swigMethodTypes3))
      swigDelegate3 = new SwigDelegateIMarketEvent_3(SwigDirectorMethodOnRspRawData);
    if (SwigDerivedClassHasMethod("OnRspUserLogin", swigMethodTypes4))
      swigDelegate4 = new SwigDelegateIMarketEvent_4(SwigDirectorMethodOnRspUserLogin);
    if (SwigDerivedClassHasMethod("OnRspTradeDate", swigMethodTypes5))
      swigDelegate5 = new SwigDelegateIMarketEvent_5(SwigDirectorMethodOnRspTradeDate);
    if (SwigDerivedClassHasMethod("OnRspBrokerData", swigMethodTypes6))
      swigDelegate6 = new SwigDelegateIMarketEvent_6(SwigDirectorMethodOnRspBrokerData);
    if (SwigDerivedClassHasMethod("OnRspMarketData", swigMethodTypes7))
      swigDelegate7 = new SwigDelegateIMarketEvent_7(SwigDirectorMethodOnRspMarketData);
    if (SwigDerivedClassHasMethod("OnRspUserLogout", swigMethodTypes8))
      swigDelegate8 = new SwigDelegateIMarketEvent_8(SwigDirectorMethodOnRspUserLogout);
    DaApiWrapperPINVOKE.IMarketEvent_director_connect(swigCPtr, swigDelegate0, swigDelegate1, swigDelegate2, swigDelegate3, swigDelegate4, swigDelegate5, swigDelegate6, swigDelegate7, swigDelegate8);
  }

  private bool SwigDerivedClassHasMethod(string methodName, global::System.Type[] methodTypes) {
    global::System.Reflection.MethodInfo[] methodInfos = this.GetType().GetMethods(
        global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance);
    foreach (global::System.Reflection.MethodInfo methodInfo in methodInfos) {
      if (methodInfo.DeclaringType == null)
        continue;

      if (methodInfo.Name != methodName)
        continue;

      var parameters = methodInfo.GetParameters();
      if (parameters.Length != methodTypes.Length)
        continue;

      bool parametersMatch = true;
      for (var i = 0; i < parameters.Length; i++) {
        if (parameters[i].ParameterType != methodTypes[i]) {
          parametersMatch = false;
          break;
        }
      }

      if (!parametersMatch)
        continue;

      if (methodInfo.IsVirtual && (methodInfo.DeclaringType.IsSubclassOf(typeof(IMarketEvent))) &&
        methodInfo.DeclaringType != methodInfo.GetBaseDefinition().DeclaringType) {
        return true;
      }
    }

    return false;
  }

  private void SwigDirectorMethodOnFrontConnected() {
    OnFrontConnected();
  }

  private void SwigDirectorMethodOnFrontDisconnected(int iReason) {
    OnFrontDisconnected(iReason);
  }

  private void SwigDirectorMethodOnHeartBeatWarning(int iTimeLapse) {
    OnHeartBeatWarning(iTimeLapse);
  }

  private void SwigDirectorMethodOnRspRawData(string rawData) {
    OnRspRawData(rawData);
  }

  private void SwigDirectorMethodOnRspUserLogin(global::System.IntPtr pRspInfo, int iRequestID, bool bIsLast) {
    OnRspUserLogin((pRspInfo == global::System.IntPtr.Zero) ? null : new CMarketRspInfoField(pRspInfo, false), iRequestID, bIsLast);
  }

  private void SwigDirectorMethodOnRspTradeDate(global::System.IntPtr pRspTradeDate, global::System.IntPtr pRspInfo, int iRequestID, bool bIsLast) {
    OnRspTradeDate((pRspTradeDate == global::System.IntPtr.Zero) ? null : new CMarketRspTradeDateField(pRspTradeDate, false), (pRspInfo == global::System.IntPtr.Zero) ? null : new CMarketRspInfoField(pRspInfo, false), iRequestID, bIsLast);
  }

  private void SwigDirectorMethodOnRspBrokerData(global::System.IntPtr pRspBrokerData, global::System.IntPtr pRspInfo, int iRequestID, bool bIsLast) {
    OnRspBrokerData((pRspBrokerData == global::System.IntPtr.Zero) ? null : new CMarketRspBrokerDataField(pRspBrokerData, false), (pRspInfo == global::System.IntPtr.Zero) ? null : new CMarketRspInfoField(pRspInfo, false), iRequestID, bIsLast);
  }

  private void SwigDirectorMethodOnRspMarketData(global::System.IntPtr pRspMarketData, global::System.IntPtr pRspInfo, int iRequestID, bool bIsLast) {
    OnRspMarketData((pRspMarketData == global::System.IntPtr.Zero) ? null : new CMarketRspMarketDataField(pRspMarketData, false), (pRspInfo == global::System.IntPtr.Zero) ? null : new CMarketRspInfoField(pRspInfo, false), iRequestID, bIsLast);
  }

  private void SwigDirectorMethodOnRspUserLogout(global::System.IntPtr pRspInfo, int iRequestID, bool bIsLast) {
    OnRspUserLogout((pRspInfo == global::System.IntPtr.Zero) ? null : new CMarketRspInfoField(pRspInfo, false), iRequestID, bIsLast);
  }

  public delegate void SwigDelegateIMarketEvent_0();
  public delegate void SwigDelegateIMarketEvent_1(int iReason);
  public delegate void SwigDelegateIMarketEvent_2(int iTimeLapse);
  public delegate void SwigDelegateIMarketEvent_3(string rawData);
  public delegate void SwigDelegateIMarketEvent_4(global::System.IntPtr pRspInfo, int iRequestID, bool bIsLast);
  public delegate void SwigDelegateIMarketEvent_5(global::System.IntPtr pRspTradeDate, global::System.IntPtr pRspInfo, int iRequestID, bool bIsLast);
  public delegate void SwigDelegateIMarketEvent_6(global::System.IntPtr pRspBrokerData, global::System.IntPtr pRspInfo, int iRequestID, bool bIsLast);
  public delegate void SwigDelegateIMarketEvent_7(global::System.IntPtr pRspMarketData, global::System.IntPtr pRspInfo, int iRequestID, bool bIsLast);
  public delegate void SwigDelegateIMarketEvent_8(global::System.IntPtr pRspInfo, int iRequestID, bool bIsLast);

  private SwigDelegateIMarketEvent_0 swigDelegate0;
  private SwigDelegateIMarketEvent_1 swigDelegate1;
  private SwigDelegateIMarketEvent_2 swigDelegate2;
  private SwigDelegateIMarketEvent_3 swigDelegate3;
  private SwigDelegateIMarketEvent_4 swigDelegate4;
  private SwigDelegateIMarketEvent_5 swigDelegate5;
  private SwigDelegateIMarketEvent_6 swigDelegate6;
  private SwigDelegateIMarketEvent_7 swigDelegate7;
  private SwigDelegateIMarketEvent_8 swigDelegate8;

  private static global::System.Type[] swigMethodTypes0 = new global::System.Type[] {  };
  private static global::System.Type[] swigMethodTypes1 = new global::System.Type[] { typeof(int) };
  private static global::System.Type[] swigMethodTypes2 = new global::System.Type[] { typeof(int) };
  private static global::System.Type[] swigMethodTypes3 = new global::System.Type[] { typeof(string) };
  private static global::System.Type[] swigMethodTypes4 = new global::System.Type[] { typeof(CMarketRspInfoField), typeof(int), typeof(bool) };
  private static global::System.Type[] swigMethodTypes5 = new global::System.Type[] { typeof(CMarketRspTradeDateField), typeof(CMarketRspInfoField), typeof(int), typeof(bool) };
  private static global::System.Type[] swigMethodTypes6 = new global::System.Type[] { typeof(CMarketRspBrokerDataField), typeof(CMarketRspInfoField), typeof(int), typeof(bool) };
  private static global::System.Type[] swigMethodTypes7 = new global::System.Type[] { typeof(CMarketRspMarketDataField), typeof(CMarketRspInfoField), typeof(int), typeof(bool) };
  private static global::System.Type[] swigMethodTypes8 = new global::System.Type[] { typeof(CMarketRspInfoField), typeof(int), typeof(bool) };
}

}
